// src/main/webapp/app/entities/medicamentos/medicamentos-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IPosologias } from 'app/shared/model/posologias.model';
import { getEntities as getPosologias } from 'app/entities/posologias/posologias.reducer';
import { IFabricantes } from 'app/shared/model/fabricantes.model';
import { getEntities as getFabricantes } from 'app/entities/fabricantes/fabricantes.reducer';
import { getEntity, updateEntity, createEntity, reset } from './medicamentos.reducer';
import { IMedicamentos } from 'app/shared/model/medicamentos.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer, convertDateTimeToServer } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IMedicamentosUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export interface IMedicamentosUpdateState {
  isNew: boolean;
  posologiaPadraoId: string;
  fabricantesId: string;
}

export class MedicamentosUpdate extends React.Component<IMedicamentosUpdateProps, IMedicamentosUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      posologiaPadraoId: '0',
      fabricantesId: '0',
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentWillUpdate(nextProps, nextState) {
    if (nextProps.updateSuccess !== this.props.updateSuccess && nextProps.updateSuccess) {
      this.handleClose();
    }
  }

  componentDidMount() {
    if (!this.state.isNew) {
      this.props.getEntity(this.props.match.params.id);
    }

    this.props.getPosologias();
    this.props.getFabricantes();
  }

  saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const { medicamentosEntity } = this.props;
      const entity = {
        ...medicamentosEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/medicamentos');
  };

  render() {
    const { medicamentosEntity, posologias, fabricantes, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="safhApp.medicamentos.home.createOrEditLabel">Create or edit a Medicamentos</h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : medicamentosEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="medicamentos-id">ID</Label>
                    <AvInput id="medicamentos-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="descricaoLabel" for="medicamentos-descricao">
                    Descricao
                  </Label>
                  <AvField
                    id="medicamentos-descricao"
                    type="text"
                    name="descricao"
                    validate={{
                      required: { value: true, errorMessage: 'This field is required.' },
                      maxLength: { value: 100, errorMessage: 'This field cannot be longer than 100 characters.' }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="registroMinisterioSaudeLabel" for="medicamentos-registroMinisterioSaude">
                    Registro Ministerio Saude
                  </Label>
                  <AvField
                    id="medicamentos-registroMinisterioSaude"
                    type="text"
                    name="registroMinisterioSaude"
                    validate={{
                      required: { value: true, errorMessage: 'This field is required.' },
                      maxLength: { value: 60, errorMessage: 'This field cannot be longer than 60 characters.' }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="codigoBarrasLabel" for="medicamentos-codigoBarras">
                    Codigo Barras
                  </Label>
                  <AvField
                    id="medicamentos-codigoBarras"
                    type="text"
                    name="codigoBarras"
                    validate={{
                      required: { value: true, errorMessage: 'This field is required.' },
                      maxLength: { value: 13, errorMessage: 'This field cannot be longer than 13 characters.' }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="qtdAtualLabel" for="medicamentos-qtdAtual">
                    Qtd Atual
                  </Label>
                  <AvField id="medicamentos-qtdAtual" type="string" className="form-control" name="qtdAtual" />
                </AvGroup>
                <AvGroup>
                  <Label id="qtdMinLabel" for="medicamentos-qtdMin">
                    Qtd Min
                  </Label>
                  <AvField id="medicamentos-qtdMin" type="string" className="form-control" name="qtdMin" />
                </AvGroup>
                <AvGroup>
                  <Label id="qtdMaxLabel" for="medicamentos-qtdMax">
                    Qtd Max
                  </Label>
                  <AvField id="medicamentos-qtdMax" type="string" className="form-control" name="qtdMax" />
                </AvGroup>
                <AvGroup>
                  <Label id="observacoesLabel" for="medicamentos-observacoes">
                    Observacoes
                  </Label>
                  <AvField
                    id="medicamentos-observacoes"
                    type="text"
                    name="observacoes"
                    validate={{
                      maxLength: { value: 8000, errorMessage: 'This field cannot be longer than 8000 characters.' }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="apresentacaoLabel" for="medicamentos-apresentacao">
                    Apresentacao
                  </Label>
                  <AvField id="medicamentos-apresentacao" type="text" name="apresentacao" />
                </AvGroup>
                <AvGroup>
                  <Label for="medicamentos-posologiaPadrao">Posologia Padrao</Label>
                  <AvInput id="medicamentos-posologiaPadrao" type="select" className="form-control" name="posologiaPadrao.id">
                    <option value="" key="0" />
                    {posologias
                      ? posologias.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.posologia}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="medicamentos-fabricantes">Fabricantes</Label>
                  <AvInput id="medicamentos-fabricantes" type="select" className="form-control" name="fabricantes.id">
                    <option value="" key="0" />
                    {fabricantes
                      ? fabricantes.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.fabricante}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/medicamentos" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />
                  &nbsp;
                  <span className="d-none d-md-inline">Back</span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />
                  &nbsp; Save
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  posologias: storeState.posologias.entities,
  fabricantes: storeState.fabricantes.entities,
  medicamentosEntity: storeState.medicamentos.entity,
  loading: storeState.medicamentos.loading,
  updating: storeState.medicamentos.updating,
  updateSuccess: storeState.medicamentos.updateSuccess
});

const mapDispatchToProps = {
  getPosologias,
  getFabricantes,
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(MedicamentosUpdate);

// src/main/webapp/app/entities/medicamentos/update/medicamentos-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { IMedicamentos, Medicamentos } from '../medicamentos.model';
import { MedicamentosService } from '../service/medicamentos.service';
import { IPosologias } from 'app/entities/posologias/posologias.model';
import { PosologiasService } from 'app/entities/posologias/service/posologias.service';
import { IFabricantes } from 'app/entities/fabricantes/fabricantes.model';
import { FabricantesService } from 'app/entities/fabricantes/service/fabricantes.service';

@Component({
  selector: 'jhi-medicamentos-update',
  templateUrl: './medicamentos-update.component.html',
})
export class MedicamentosUpdateComponent implements OnInit {
  isSaving = false;

  posologiasSharedCollection: IPosologias[] = [];
  fabricantesSharedCollection: IFabricantes[] = [];

  editForm = this.fb.group({
    id: [],
    descricao: [null, [Validators.required, Validators.maxLength(100)]],
    registroMinisterioSaude: [null, [Validators.required, Validators.maxLength(60)]],
    codigoBarras: [null, [Validators.required, Validators.maxLength(13)]],
    qtdAtual: [],
    qtdMin: [],
    qtdMax: [],
    observacoes: [null, [Validators.maxLength(8000)]],
    apresentacao: [],
    posologiaPadrao: [],
    fabricantes: [],
  });

  constructor(
    protected medicamentosService: MedicamentosService,
    protected posologiasService: PosologiasService,
    protected fabricantesService: FabricantesService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ medicamentos }) => {
      this.updateForm(medicamentos);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const medicamentos = this.createFromForm();
    if (medicamentos.id !== undefined) {
      this.subscribeToSaveResponse(this.medicamentosService.update(medicamentos));
    } else {
      this.subscribeToSaveResponse(this.medicamentosService.create(medicamentos));
    }
  }

  trackPosologiasById(index: number, item: IPosologias): number {
    return item.id!;
  }

  trackFabricantesById(index: number, item: IFabricantes): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IMedicamentos>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(medicamentos: IMedicamentos): void {
    this.editForm.patchValue({
      id: medicamentos.id,
      descricao: medicamentos.descricao,
      registroMinisterioSaude: medicamentos.registroMinisterioSaude,
      codigoBarras: medicamentos.codigoBarras,
      qtdAtual: medicamentos.qtdAtual,
      qtdMin: medicamentos.qtdMin,
      qtdMax: medicamentos.qtdMax,
      observacoes: medicamentos.observacoes,
      apresentacao: medicamentos.apresentacao,
      posologiaPadrao: medicamentos.posologiaPadrao,
      fabricantes: medicamentos.fabricantes,
    });

    this.posologiasSharedCollection = this.posologiasService.addPosologiasToCollectionIfMissing(
      this.posologiasSharedCollection,
      medicamentos.posologiaPadrao
    );
    this.fabricantesSharedCollection = this.fabricantesService.addFabricantesToCollectionIfMissing(
      this.fabricantesSharedCollection,
      medicamentos.fabricantes
    );
  }

  protected loadRelationshipsOptions(): void {
    this.posologiasService
      .query()
      .pipe(map((res: HttpResponse<IPosologias[]>) => res.body ?? []))
      .pipe(
        map((posologias: IPosologias[]) =>
          this.posologiasService.addPosologiasToCollectionIfMissing(posologias, this.editForm.get('posologiaPadrao')!.value)
        )
      )
      .subscribe((posologias: IPosologias[]) => (this.posologiasSharedCollection = posologias));

    this.fabricantesService
      .query()
      .pipe(map((res: HttpResponse<IFabricantes[]>) => res.body ?? []))
      .pipe(
        map((fabricantes: IFabricantes[]) =>
          this.fabricantesService.addFabricantesToCollectionIfMissing(fabricantes, this.editForm.get('fabricantes')!.value)
        )
      )
      .subscribe((fabricantes: IFabricantes[]) => (this.fabricantesSharedCollection = fabricantes));
  }

  protected createFromForm(): IMedicamentos {
    return {
      ...new Medicamentos(),
      id: this.editForm.get(['id'])!.value,
      descricao: this.editForm.get(['descricao'])!.value,
      registroMinisterioSaude: this.editForm.get(['registroMinisterioSaude'])!.value,
      codigoBarras: this.editForm.get(['codigoBarras'])!.value,
      qtdAtual: this.editForm.get(['qtdAtual'])!.value,
      qtdMin: this.editForm.get(['qtdMin'])!.value,
      qtdMax: this.editForm.get(['qtdMax'])!.value,
      observacoes: this.editForm.get(['observacoes'])!.value,
      apresentacao: this.editForm.get(['apresentacao'])!.value,
      posologiaPadrao: this.editForm.get(['posologiaPadrao'])!.value,
      fabricantes: this.editForm.get(['fabricantes'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2
        id="jhi-medicamentos-heading"
        data-cy="MedicamentosCreateUpdateHeading"
        jhiTranslate="safhApp.medicamentos.home.createOrEditLabel"
      >
        Create or edit a Medicamentos
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="safhApp.medicamentos.descricao" for="field_descricao">Descricao</label>
          <input type="text" class="form-control" name="descricao" id="field_descricao" data-cy="descricao" formControlName="descricao" />
          <div *ngIf="editForm.get('descricao')!.invalid && (editForm.get('descricao')!.dirty || editForm.get('descricao')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('descricao')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('descricao')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 100 }"
            >
              This field cannot be longer than 100 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="safhApp.medicamentos.registroMinisterioSaude" for="field_registroMinisterioSaude"
            >Registro Ministerio Saude</label
          >
          <input
            type="text"
            class="form-control"
            name="registroMinisterioSaude"
            id="field_registroMinisterioSaude"
            data-cy="registroMinisterioSaude"
            formControlName="registroMinisterioSaude"
          />
          <div
            *ngIf="
              editForm.get('registroMinisterioSaude')!.invalid &&
              (editForm.get('registroMinisterioSaude')!.dirty || editForm.get('registroMinisterioSaude')!.touched)
            "
          >
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('registroMinisterioSaude')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('registroMinisterioSaude')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 60 }"
            >
              This field cannot be longer than 60 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="safhApp.medicamentos.codigoBarras" for="field_codigoBarras">Codigo Barras</label>
          <input
            type="text"
            class="form-control"
            name="codigoBarras"
            id="field_codigoBarras"
            data-cy="codigoBarras"
            formControlName="codigoBarras"
          />
          <div
            *ngIf="editForm.get('codigoBarras')!.invalid && (editForm.get('codigoBarras')!.dirty || editForm.get('codigoBarras')!.touched)"
          >
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('codigoBarras')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('codigoBarras')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 13 }"
            >
              This field cannot be longer than 13 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="safhApp.medicamentos.qtdAtual" for="field_qtdAtual">Qtd Atual</label>
          <input type="number" class="form-control" name="qtdAtual" id="field_qtdAtual" data-cy="qtdAtual" formControlName="qtdAtual" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="safhApp.medicamentos.qtdMin" for="field_qtdMin">Qtd Min</label>
          <input type="number" class="form-control" name="qtdMin" id="field_qtdMin" data-cy="qtdMin" formControlName="qtdMin" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="safhApp.medicamentos.qtdMax" for="field_qtdMax">Qtd Max</label>
          <input type="number" class="form-control" name="qtdMax" id="field_qtdMax" data-cy="qtdMax" formControlName="qtdMax" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="safhApp.medicamentos.observacoes" for="field_observacoes">Observacoes</label>
          <input
            type="text"
            class="form-control"
            name="observacoes"
            id="field_observacoes"
            data-cy="observacoes"
            formControlName="observacoes"
          />
          <div *ngIf="editForm.get('observacoes')!.invalid && (editForm.get('observacoes')!.dirty || editForm.get('observacoes')!.touched)">
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('observacoes')?.errors?.maxlength"
              jhiTranslate="entity.validation.maxlength"
              [translateValues]="{ max: 8000 }"
            >
              This field cannot be longer than 8000 characters.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="safhApp.medicamentos.apresentacao" for="field_apresentacao">Apresentacao</label>
          <input
            type="text"
            class="form-control"
            name="apresentacao"
            id="field_apresentacao"
            data-cy="apresentacao"
            formControlName="apresentacao"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="safhApp.medicamentos.posologiaPadrao" for="field_posologiaPadrao"
            >Posologia Padrao</label
          >
          <select
            class="form-control"
            id="field_posologiaPadrao"
            data-cy="posologiaPadrao"
            name="posologiaPadrao"
            formControlName="posologiaPadrao"
          >
            <option [ngValue]="null"></option>
            <option
              [ngValue]="
                posologiasOption.id === editForm.get('posologiaPadrao')!.value?.id
                  ? editForm.get('posologiaPadrao')!.value
                  : posologiasOption
              "
              *ngFor="let posologiasOption of posologiasSharedCollection; trackBy: trackPosologiasById"
            >
              {{ posologiasOption.posologia }}
            </option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="safhApp.medicamentos.fabricantes" for="field_fabricantes">Fabricantes</label>
          <select class="form-control" id="field_fabricantes" data-cy="fabricantes" name="fabricantes" formControlName="fabricantes">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="
                fabricantesOption.id === editForm.get('fabricantes')!.value?.id ? editForm.get('fabricantes')!.value : fabricantesOption
              "
              *ngFor="let fabricantesOption of fabricantesSharedCollection; trackBy: trackFabricantesById"
            >
              {{ fabricantesOption.fabricante }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
