// src/main/webapp/app/entities/internacoes/detail/internacoes-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IInternacoes } from '../internacoes.model';

@Component({
  selector: 'jhi-internacoes-detail',
  templateUrl: './internacoes-detail.component.html',
})
export class InternacoesDetailComponent implements OnInit {
  internacoes: IInternacoes | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ internacoes }) => {
      this.internacoes = internacoes;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <div *ngIf="internacoes">
      <h2 data-cy="internacoesDetailsHeading"><span jhiTranslate="safhApp.internacoes.detail.title">Internacoes</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ internacoes.id }}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoes.dataInternacao">Data Internacao</span></dt>
        <dd>
          <span>{{ internacoes.dataInternacao | formatMediumDate }}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoes.descricao">Descricao</span></dt>
        <dd>
          <span>{{ internacoes.descricao }}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoes.pacientes">Pacientes</span></dt>
        <dd>
          <div *ngIf="internacoes.pacientes">
            <a [routerLink]="['/pacientes', internacoes.pacientes?.id, 'view']">{{ internacoes.pacientes?.nome }}</a>
          </div>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoes.clinicas">Clinicas</span></dt>
        <dd>
          <div *ngIf="internacoes.clinicas">
            <a [routerLink]="['/clinicas', internacoes.clinicas?.id, 'view']">{{ internacoes.clinicas?.clinica }}</a>
          </div>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoes.medicos">Medicos</span></dt>
        <dd>
          <div *ngIf="internacoes.medicos">
            <a [routerLink]="['/medicos', internacoes.medicos?.id, 'view']">{{ internacoes.medicos?.nome }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/internacoes', internacoes.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>

// src/main/webapp/app/entities/internacoes/internacoes-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, ICrudGetAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './internacoes.reducer';
import { IInternacoes } from 'app/shared/model/internacoes.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IInternacoesDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class InternacoesDetail extends React.Component<IInternacoesDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { internacoesEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="safhApp.internacoes.detail.title">Internacoes</Translate> [<b>{internacoesEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="dataInternacao">
                <Translate contentKey="safhApp.internacoes.dataInternacao">Data Internacao</Translate>
              </span>
            </dt>
            <dd>
              <TextFormat value={internacoesEntity.dataInternacao} type="date" format={APP_LOCAL_DATE_FORMAT} />
            </dd>
            <dt>
              <span id="descricao">
                <Translate contentKey="safhApp.internacoes.descricao">Descricao</Translate>
              </span>
            </dt>
            <dd>{internacoesEntity.descricao}</dd>
            <dt>
              <Translate contentKey="safhApp.internacoes.pacientes">Pacientes</Translate>
            </dt>
            <dd>{internacoesEntity.pacientes ? internacoesEntity.pacientes.nome : ''}</dd>
            <dt>
              <Translate contentKey="safhApp.internacoes.clinicas">Clinicas</Translate>
            </dt>
            <dd>{internacoesEntity.clinicas ? internacoesEntity.clinicas.clinica : ''}</dd>
            <dt>
              <Translate contentKey="safhApp.internacoes.medicos">Medicos</Translate>
            </dt>
            <dd>{internacoesEntity.medicos ? internacoesEntity.medicos.nome : ''}</dd>
          </dl>
          <Button tag={Link} to="/internacoes" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/internacoes/${internacoesEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ internacoes }: IRootState) => ({
  internacoesEntity: internacoes.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(InternacoesDetail);
