// src/main/webapp/app/entities/internacoes/internacoes-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, ICrudGetAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './internacoes.reducer';
import { IInternacoes } from 'app/shared/model/internacoes.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IInternacoesDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class InternacoesDetail extends React.Component<IInternacoesDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { internacoesEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="safhApp.internacoes.detail.title">Internacoes</Translate> [<b>{internacoesEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="dataInternacao">
                <Translate contentKey="safhApp.internacoes.dataInternacao">Data Internacao</Translate>
              </span>
            </dt>
            <dd>
              <TextFormat value={internacoesEntity.dataInternacao} type="date" format={APP_LOCAL_DATE_FORMAT} />
            </dd>
            <dt>
              <span id="descricao">
                <Translate contentKey="safhApp.internacoes.descricao">Descricao</Translate>
              </span>
            </dt>
            <dd>{internacoesEntity.descricao}</dd>
            <dt>
              <Translate contentKey="safhApp.internacoes.pacientes">Pacientes</Translate>
            </dt>
            <dd>{internacoesEntity.pacientes ? internacoesEntity.pacientes.nome : ''}</dd>
            <dt>
              <Translate contentKey="safhApp.internacoes.clinicas">Clinicas</Translate>
            </dt>
            <dd>{internacoesEntity.clinicas ? internacoesEntity.clinicas.clinica : ''}</dd>
            <dt>
              <Translate contentKey="safhApp.internacoes.medicos">Medicos</Translate>
            </dt>
            <dd>{internacoesEntity.medicos ? internacoesEntity.medicos.nome : ''}</dd>
          </dl>
          <Button tag={Link} to="/internacoes" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/internacoes/${internacoesEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ internacoes }: IRootState) => ({
  internacoesEntity: internacoes.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(InternacoesDetail);

// src/main/webapp/app/entities/internacoes/internacoes-detail.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs/Rx';
import { JhiEventManager } from 'ng-jhipster';

import { Internacoes } from './internacoes.model';
import { InternacoesService } from './internacoes.service';

@Component({
    selector: 'jhi-internacoes-detail',
    templateUrl: './internacoes-detail.component.html'
})
export class InternacoesDetailComponent implements OnInit, OnDestroy {

    internacoes: Internacoes;
    private subscription: Subscription;
    private eventSubscriber: Subscription;

    constructor(
        private eventManager: JhiEventManager,
        private internacoesService: InternacoesService,
        private route: ActivatedRoute
    ) {
    }

    ngOnInit() {
        this.subscription = this.route.params.subscribe((params) => {
            this.load(params['id']);
        });
        this.registerChangeInInternacoes();
    }

    load(id) {
        this.internacoesService.find(id).subscribe((internacoes) => {
            this.internacoes = internacoes;
        });
    }
    previousState() {
        window.history.back();
    }

    ngOnDestroy() {
        this.subscription.unsubscribe();
        this.eventManager.destroy(this.eventSubscriber);
    }

    registerChangeInInternacoes() {
        this.eventSubscriber = this.eventManager.subscribe(
            'internacoesListModification',
            (response) => this.load(this.internacoes.id)
        );
    }
}


<div *ngIf="internacoes">
    <h2><span jhiTranslate="safhApp.internacoes.detail.title">Internacoes</span> {{internacoes.id}}</h2>
    <hr>
    <jhi-alert-error></jhi-alert-error>
    <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="safhApp.internacoes.dataInternacao">Data Internacao</span></dt>
        <dd>
            <span>{{internacoes.dataInternacao | date:'mediumDate'}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoes.descricao">Descricao</span></dt>
        <dd>
            <span>{{internacoes.descricao}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoes.pacientes">Pacientes</span></dt>
        <dd>
            <div *ngIf="internacoes.pacientes">
                <a [routerLink]="['/pacientes', internacoes.pacientes?.id]">{{internacoes.pacientes?.nome}}</a>
            </div>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoes.clinicas">Clinicas</span></dt>
        <dd>
            <div *ngIf="internacoes.clinicas">
                <a [routerLink]="['/clinicas', internacoes.clinicas?.id]">{{internacoes.clinicas?.clinica}}</a>
            </div>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoes.medicos">Medicos</span></dt>
        <dd>
            <div *ngIf="internacoes.medicos">
                <a [routerLink]="['/medicos', internacoes.medicos?.id]">{{internacoes.medicos?.nome}}</a>
            </div>
        </dd>
    </dl>

    <button type="submit"
            (click)="previousState()"
            class="btn btn-info">
        <span class="fa fa-arrow-left"></span>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
    </button>

    <button type="button"
            [routerLink]="['/', { outlets: { popup: 'internacoes/'+ internacoes.id + '/edit'} }]"
            replaceUrl="true"
            class="btn btn-primary">
        <span class="fa fa-pencil"></span>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
    </button>
</div>
