// src/main/webapp/app/entities/internacoes-detalhes/internacoes-detalhes.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs/Rx';
import { JhiEventManager, JhiParseLinks, JhiAlertService } from 'ng-jhipster';

import { InternacoesDetalhes } from './internacoes-detalhes.model';
import { InternacoesDetalhesService } from './internacoes-detalhes.service';
import { ITEMS_PER_PAGE, Principal, ResponseWrapper } from '../../shared';

@Component({
    selector: 'jhi-internacoes-detalhes',
    templateUrl: './internacoes-detalhes.component.html'
})
export class InternacoesDetalhesComponent implements OnInit, OnDestroy {

    internacoesDetalhes: InternacoesDetalhes[];
    currentAccount: any;
    eventSubscriber: Subscription;
    itemsPerPage: number;
    links: any;
    page: any;
    predicate: any;
    queryCount: any;
    reverse: any;
    totalItems: number;
    currentSearch: string;

    constructor(
        private internacoesDetalhesService: InternacoesDetalhesService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private parseLinks: JhiParseLinks,
        private activatedRoute: ActivatedRoute,
        private principal: Principal
    ) {
        this.internacoesDetalhes = [];
        this.itemsPerPage = ITEMS_PER_PAGE;
        this.page = 0;
        this.links = {
            last: 0
        };
        this.predicate = 'id';
        this.reverse = true;
        this.currentSearch = activatedRoute.snapshot.params['search'] ? activatedRoute.snapshot.params['search'] : '';
    }

    loadAll() {
        if (this.currentSearch) {
            this.internacoesDetalhesService.search({
                query: this.currentSearch,
                page: this.page,
                size: this.itemsPerPage,
                sort: this.sort()
            }).subscribe(
                (res: ResponseWrapper) => this.onSuccess(res.json, res.headers),
                (res: ResponseWrapper) => this.onError(res.json)
            );
            return;
        }
        this.internacoesDetalhesService.query({
            page: this.page,
            size: this.itemsPerPage,
            sort: this.sort()
        }).subscribe(
            (res: ResponseWrapper) => this.onSuccess(res.json, res.headers),
            (res: ResponseWrapper) => this.onError(res.json)
        );
    }

    reset() {
        this.page = 0;
        this.internacoesDetalhes = [];
        this.loadAll();
    }

    loadPage(page) {
        this.page = page;
        this.loadAll();
    }

    clear() {
        this.internacoesDetalhes = [];
        this.links = {
            last: 0
        };
        this.page = 0;
        this.predicate = 'id';
        this.reverse = true;
        this.currentSearch = '';
        this.loadAll();
    }

    search(query) {
        if (!query) {
            return this.clear();
        }
        this.internacoesDetalhes = [];
        this.links = {
            last: 0
        };
        this.page = 0;
        this.predicate = '_score';
        this.reverse = false;
        this.currentSearch = query;
        this.loadAll();
    }
    ngOnInit() {
        this.loadAll();
        this.principal.identity().then((account) => {
            this.currentAccount = account;
        });
        this.registerChangeInInternacoesDetalhes();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: InternacoesDetalhes) {
        return item.id;
    }
    registerChangeInInternacoesDetalhes() {
        this.eventSubscriber = this.eventManager.subscribe('internacoesDetalhesListModification', (response) => this.reset());
    }

    sort() {
        const result = [this.predicate + ',' + (this.reverse ? 'asc' : 'desc')];
        if (this.predicate !== 'id') {
            result.push('id');
        }
        return result;
    }

    private onSuccess(data, headers) {
        this.links = this.parseLinks.parse(headers.get('link'));
        this.totalItems = headers.get('X-Total-Count');
        for (let i = 0; i < data.length; i++) {
            this.internacoesDetalhes.push(data[i]);
        }
    }

    private onError(error) {
        this.jhiAlertService.error(error.message, null, null);
    }
}

<div>
    <h2>
        <span jhiTranslate="safhApp.internacoesDetalhes.home.title">Internacoes Detalhes</span>
        <button class="btn btn-primary float-right jh-create-entity create-internacoes-detalhes" [routerLink]="['/', { outlets: { popup: ['internacoes-detalhes-new'] } }]">
            <span class="fa fa-plus"></span>
            <span class="hidden-sm-down"  jhiTranslate="safhApp.internacoesDetalhes.home.createLabel">
            Create new Internacoes Detalhes
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <div class="row">
        <div class="col-sm-12">
            <form name="searchForm" class="form-inline">
                <div class="input-group w-100 mt-3">
                    <input type="text" class="form-control" [(ngModel)]="currentSearch" id="currentSearch" name="currentSearch" placeholder="{{ 'safhApp.internacoesDetalhes.home.search' | translate }}">
                    <button class="input-group-addon btn btn-info" (click)="search(currentSearch)">
                        <span class="fa fa-search"></span>
                    </button>
                    <button class="input-group-addon btn btn-danger" (click)="clear()" *ngIf="currentSearch">
                        <span class="fa fa-trash-o"></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <br/>
    <div class="table-responsive" *ngIf="internacoesDetalhes">
        <table class="table table-striped">
            <thead>
            <tr jhiSort [(predicate)]="predicate" [(ascending)]="reverse" [callback]="reset.bind(this)">
            <th jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="dataDetalhe"><span jhiTranslate="safhApp.internacoesDetalhes.dataDetalhe">Data Detalhe</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="horario"><span jhiTranslate="safhApp.internacoesDetalhes.horario">Horario</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="qtd"><span jhiTranslate="safhApp.internacoesDetalhes.qtd">Qtd</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="internacoes.descricao"><span jhiTranslate="safhApp.internacoesDetalhes.internacoes">Internacoes</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="dietas.dieta"><span jhiTranslate="safhApp.internacoesDetalhes.dietas">Dietas</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="prescricoes.prescricao"><span jhiTranslate="safhApp.internacoesDetalhes.prescricoes">Prescricoes</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="posologias.posologia"><span jhiTranslate="safhApp.internacoesDetalhes.posologias">Posologias</span> <span class="fa fa-sort"></span></th>
            <th></th>
            </tr>
            </thead>
            <tbody infinite-scroll (scrolled)="loadPage(page + 1)" [infiniteScrollDisabled]="page >= links['last']" [infiniteScrollDistance]="0">
            <tr *ngFor="let internacoesDetalhes of internacoesDetalhes ;trackBy: trackId">
                <td><a [routerLink]="['../internacoes-detalhes', internacoesDetalhes.id ]">{{internacoesDetalhes.id}}</a></td>
                <td>{{internacoesDetalhes.dataDetalhe | date:'mediumDate'}}</td>
                <td>{{internacoesDetalhes.horario | date:'mediumDate'}}</td>
                <td>{{internacoesDetalhes.qtd}}</td>
                <td>
                    <div *ngIf="internacoesDetalhes.internacoes">
                        <a [routerLink]="['../internacoes', internacoesDetalhes.internacoes?.id ]" >{{internacoesDetalhes.internacoes?.descricao}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="internacoesDetalhes.dietas">
                        <a [routerLink]="['../dietas', internacoesDetalhes.dietas?.id ]" >{{internacoesDetalhes.dietas?.dieta}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="internacoesDetalhes.prescricoes">
                        <a [routerLink]="['../prescricoes', internacoesDetalhes.prescricoes?.id ]" >{{internacoesDetalhes.prescricoes?.prescricao}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="internacoesDetalhes.posologias">
                        <a [routerLink]="['../posologias', internacoesDetalhes.posologias?.id ]" >{{internacoesDetalhes.posologias?.posologia}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['../internacoes-detalhes', internacoesDetalhes.id ]"
                                class="btn btn-info btn-sm">
                            <span class="fa fa-eye"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'internacoes-detalhes/'+ internacoesDetalhes.id + '/edit'} }]"
                                replaceUrl="true"
                                class="btn btn-primary btn-sm">
                            <span class="fa fa-pencil"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'internacoes-detalhes/'+ internacoesDetalhes.id + '/delete'} }]"
                                replaceUrl="true"
                                class="btn btn-danger btn-sm">
                            <span class="fa fa-remove"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/internacoes-detalhes/internacoes-detalhes.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudSearchAction, ICrudGetAllAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities } from './internacoes-detalhes.reducer';
import { IInternacoesDetalhes } from 'app/shared/model/internacoes-detalhes.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IInternacoesDetalhesProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export interface IInternacoesDetalhesState {
  search: string;
}

export class InternacoesDetalhes extends React.Component<IInternacoesDetalhesProps, IInternacoesDetalhesState> {
  state: IInternacoesDetalhesState = {
    search: ''
  };

  componentDidMount() {
    this.props.getEntities();
  }

  search = () => {
    if (this.state.search) {
      this.props.getSearchEntities(this.state.search);
    }
  };

  clear = () => {
    this.setState({ search: '' }, () => {
      this.props.getEntities();
    });
  };

  handleSearch = event => this.setState({ search: event.target.value });

  render() {
    const { internacoesDetalhesList, match } = this.props;
    return (
      <div>
        <h2 id="internacoes-detalhes-heading">
          <Translate contentKey="safhApp.internacoesDetalhes.home.title">Internacoes Detalhes</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="safhApp.internacoesDetalhes.home.createLabel">Create a new Internacoes Detalhes</Translate>
          </Link>
        </h2>
        <Row>
          <Col sm="12">
            <AvForm onSubmit={this.search}>
              <AvGroup>
                <InputGroup>
                  <AvInput
                    type="text"
                    name="search"
                    value={this.state.search}
                    onChange={this.handleSearch}
                    placeholder={translate('safhApp.internacoesDetalhes.home.search')}
                  />
                  <Button className="input-group-addon">
                    <FontAwesomeIcon icon="search" />
                  </Button>
                  <Button type="reset" className="input-group-addon" onClick={this.clear}>
                    <FontAwesomeIcon icon="trash" />
                  </Button>
                </InputGroup>
              </AvGroup>
            </AvForm>
          </Col>
        </Row>
        <div className="table-responsive">
          {internacoesDetalhesList && internacoesDetalhesList.length > 0 ? (
            <Table responsive aria-describedby="internacoes-detalhes-heading">
              <thead>
                <tr>
                  <th>
                    <Translate contentKey="global.field.id">ID</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoesDetalhes.dataDetalhe">Data Detalhe</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoesDetalhes.horario">Horario</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoesDetalhes.qtd">Qtd</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoesDetalhes.internacoes">Internacoes</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoesDetalhes.dietas">Dietas</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoesDetalhes.prescricoes">Prescricoes</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoesDetalhes.posologias">Posologias</Translate>
                  </th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {internacoesDetalhesList.map((internacoesDetalhes, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${internacoesDetalhes.id}`} color="link" size="sm">
                        {internacoesDetalhes.id}
                      </Button>
                    </td>
                    <td>
                      <TextFormat type="date" value={internacoesDetalhes.dataDetalhe} format={APP_LOCAL_DATE_FORMAT} />
                    </td>
                    <td>
                      <TextFormat type="date" value={internacoesDetalhes.horario} format={APP_LOCAL_DATE_FORMAT} />
                    </td>
                    <td>{internacoesDetalhes.qtd}</td>
                    <td>
                      {internacoesDetalhes.internacoes ? (
                        <Link to={`internacoes/${internacoesDetalhes.internacoes.id}`}>{internacoesDetalhes.internacoes.descricao}</Link>
                      ) : (
                        ''
                      )}
                    </td>
                    <td>
                      {internacoesDetalhes.dietas ? (
                        <Link to={`dietas/${internacoesDetalhes.dietas.id}`}>{internacoesDetalhes.dietas.dieta}</Link>
                      ) : (
                        ''
                      )}
                    </td>
                    <td>
                      {internacoesDetalhes.prescricoes ? (
                        <Link to={`prescricoes/${internacoesDetalhes.prescricoes.id}`}>{internacoesDetalhes.prescricoes.prescricao}</Link>
                      ) : (
                        ''
                      )}
                    </td>
                    <td>
                      {internacoesDetalhes.posologias ? (
                        <Link to={`posologias/${internacoesDetalhes.posologias.id}`}>{internacoesDetalhes.posologias.posologia}</Link>
                      ) : (
                        ''
                      )}
                    </td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${internacoesDetalhes.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.view">View</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${internacoesDetalhes.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.edit">Edit</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${internacoesDetalhes.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.delete">Delete</Translate>
                          </span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            <div className="alert alert-warning">
              <Translate contentKey="safhApp.internacoesDetalhes.home.notFound">No Internacoes Detalhes found</Translate>
            </div>
          )}
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ internacoesDetalhes }: IRootState) => ({
  internacoesDetalhesList: internacoesDetalhes.entities
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(InternacoesDetalhes);
