// src/main/webapp/app/entities/internacoes-detalhes/internacoes-detalhes-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, ICrudGetAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './internacoes-detalhes.reducer';
import { IInternacoesDetalhes } from 'app/shared/model/internacoes-detalhes.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IInternacoesDetalhesDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class InternacoesDetalhesDetail extends React.Component<IInternacoesDetalhesDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { internacoesDetalhesEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="safhApp.internacoesDetalhes.detail.title">InternacoesDetalhes</Translate> [
            <b>{internacoesDetalhesEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="dataDetalhe">
                <Translate contentKey="safhApp.internacoesDetalhes.dataDetalhe">Data Detalhe</Translate>
              </span>
            </dt>
            <dd>
              <TextFormat value={internacoesDetalhesEntity.dataDetalhe} type="date" format={APP_LOCAL_DATE_FORMAT} />
            </dd>
            <dt>
              <span id="horario">
                <Translate contentKey="safhApp.internacoesDetalhes.horario">Horario</Translate>
              </span>
            </dt>
            <dd>
              <TextFormat value={internacoesDetalhesEntity.horario} type="date" format={APP_LOCAL_DATE_FORMAT} />
            </dd>
            <dt>
              <span id="qtd">
                <Translate contentKey="safhApp.internacoesDetalhes.qtd">Qtd</Translate>
              </span>
            </dt>
            <dd>{internacoesDetalhesEntity.qtd}</dd>
            <dt>
              <Translate contentKey="safhApp.internacoesDetalhes.internacoes">Internacoes</Translate>
            </dt>
            <dd>{internacoesDetalhesEntity.internacoes ? internacoesDetalhesEntity.internacoes.descricao : ''}</dd>
            <dt>
              <Translate contentKey="safhApp.internacoesDetalhes.dietas">Dietas</Translate>
            </dt>
            <dd>{internacoesDetalhesEntity.dietas ? internacoesDetalhesEntity.dietas.dieta : ''}</dd>
            <dt>
              <Translate contentKey="safhApp.internacoesDetalhes.prescricoes">Prescricoes</Translate>
            </dt>
            <dd>{internacoesDetalhesEntity.prescricoes ? internacoesDetalhesEntity.prescricoes.prescricao : ''}</dd>
            <dt>
              <Translate contentKey="safhApp.internacoesDetalhes.posologias">Posologias</Translate>
            </dt>
            <dd>{internacoesDetalhesEntity.posologias ? internacoesDetalhesEntity.posologias.posologia : ''}</dd>
          </dl>
          <Button tag={Link} to="/internacoes-detalhes" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/internacoes-detalhes/${internacoesDetalhesEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ internacoesDetalhes }: IRootState) => ({
  internacoesDetalhesEntity: internacoesDetalhes.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(InternacoesDetalhesDetail);

// src/main/webapp/app/entities/internacoes-detalhes/internacoes-detalhes-detail.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs/Rx';
import { JhiEventManager } from 'ng-jhipster';

import { InternacoesDetalhes } from './internacoes-detalhes.model';
import { InternacoesDetalhesService } from './internacoes-detalhes.service';

@Component({
    selector: 'jhi-internacoes-detalhes-detail',
    templateUrl: './internacoes-detalhes-detail.component.html'
})
export class InternacoesDetalhesDetailComponent implements OnInit, OnDestroy {

    internacoesDetalhes: InternacoesDetalhes;
    private subscription: Subscription;
    private eventSubscriber: Subscription;

    constructor(
        private eventManager: JhiEventManager,
        private internacoesDetalhesService: InternacoesDetalhesService,
        private route: ActivatedRoute
    ) {
    }

    ngOnInit() {
        this.subscription = this.route.params.subscribe((params) => {
            this.load(params['id']);
        });
        this.registerChangeInInternacoesDetalhes();
    }

    load(id) {
        this.internacoesDetalhesService.find(id).subscribe((internacoesDetalhes) => {
            this.internacoesDetalhes = internacoesDetalhes;
        });
    }
    previousState() {
        window.history.back();
    }

    ngOnDestroy() {
        this.subscription.unsubscribe();
        this.eventManager.destroy(this.eventSubscriber);
    }

    registerChangeInInternacoesDetalhes() {
        this.eventSubscriber = this.eventManager.subscribe(
            'internacoesDetalhesListModification',
            (response) => this.load(this.internacoesDetalhes.id)
        );
    }
}


<div *ngIf="internacoesDetalhes">
    <h2><span jhiTranslate="safhApp.internacoesDetalhes.detail.title">Internacoes Detalhes</span> {{internacoesDetalhes.id}}</h2>
    <hr>
    <jhi-alert-error></jhi-alert-error>
    <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="safhApp.internacoesDetalhes.dataDetalhe">Data Detalhe</span></dt>
        <dd>
            <span>{{internacoesDetalhes.dataDetalhe | date:'mediumDate'}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoesDetalhes.horario">Horario</span></dt>
        <dd>
            <span>{{internacoesDetalhes.horario | date:'mediumDate'}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoesDetalhes.qtd">Qtd</span></dt>
        <dd>
            <span>{{internacoesDetalhes.qtd}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoesDetalhes.internacoes">Internacoes</span></dt>
        <dd>
            <div *ngIf="internacoesDetalhes.internacoes">
                <a [routerLink]="['/internacoes', internacoesDetalhes.internacoes?.id]">{{internacoesDetalhes.internacoes?.descricao}}</a>
            </div>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoesDetalhes.dietas">Dietas</span></dt>
        <dd>
            <div *ngIf="internacoesDetalhes.dietas">
                <a [routerLink]="['/dietas', internacoesDetalhes.dietas?.id]">{{internacoesDetalhes.dietas?.dieta}}</a>
            </div>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoesDetalhes.prescricoes">Prescricoes</span></dt>
        <dd>
            <div *ngIf="internacoesDetalhes.prescricoes">
                <a [routerLink]="['/prescricoes', internacoesDetalhes.prescricoes?.id]">{{internacoesDetalhes.prescricoes?.prescricao}}</a>
            </div>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoesDetalhes.posologias">Posologias</span></dt>
        <dd>
            <div *ngIf="internacoesDetalhes.posologias">
                <a [routerLink]="['/posologias', internacoesDetalhes.posologias?.id]">{{internacoesDetalhes.posologias?.posologia}}</a>
            </div>
        </dd>
    </dl>

    <button type="submit"
            (click)="previousState()"
            class="btn btn-info">
        <span class="fa fa-arrow-left"></span>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
    </button>

    <button type="button"
            [routerLink]="['/', { outlets: { popup: 'internacoes-detalhes/'+ internacoesDetalhes.id + '/edit'} }]"
            replaceUrl="true"
            class="btn btn-primary">
        <span class="fa fa-pencil"></span>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
    </button>
</div>
