// src/main/webapp/app/entities/internacoes-detalhes/detail/internacoes-detalhes-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IInternacoesDetalhes } from '../internacoes-detalhes.model';

@Component({
  selector: 'jhi-internacoes-detalhes-detail',
  templateUrl: './internacoes-detalhes-detail.component.html',
})
export class InternacoesDetalhesDetailComponent implements OnInit {
  internacoesDetalhes: IInternacoesDetalhes | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ internacoesDetalhes }) => {
      this.internacoesDetalhes = internacoesDetalhes;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <div *ngIf="internacoesDetalhes">
      <h2 data-cy="internacoesDetalhesDetailsHeading">
        <span jhiTranslate="safhApp.internacoesDetalhes.detail.title">Internacoes Detalhes</span>
      </h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ internacoesDetalhes.id }}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoesDetalhes.dataDetalhe">Data Detalhe</span></dt>
        <dd>
          <span>{{ internacoesDetalhes.dataDetalhe | formatMediumDate }}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoesDetalhes.horario">Horario</span></dt>
        <dd>
          <span>{{ internacoesDetalhes.horario | formatMediumDate }}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoesDetalhes.qtd">Qtd</span></dt>
        <dd>
          <span>{{ internacoesDetalhes.qtd }}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoesDetalhes.internacoes">Internacoes</span></dt>
        <dd>
          <div *ngIf="internacoesDetalhes.internacoes">
            <a [routerLink]="['/internacoes', internacoesDetalhes.internacoes?.id, 'view']">{{
              internacoesDetalhes.internacoes?.descricao
            }}</a>
          </div>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoesDetalhes.dietas">Dietas</span></dt>
        <dd>
          <div *ngIf="internacoesDetalhes.dietas">
            <a [routerLink]="['/dietas', internacoesDetalhes.dietas?.id, 'view']">{{ internacoesDetalhes.dietas?.dieta }}</a>
          </div>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoesDetalhes.prescricoes">Prescricoes</span></dt>
        <dd>
          <div *ngIf="internacoesDetalhes.prescricoes">
            <a [routerLink]="['/prescricoes', internacoesDetalhes.prescricoes?.id, 'view']">{{
              internacoesDetalhes.prescricoes?.prescricao
            }}</a>
          </div>
        </dd>
        <dt><span jhiTranslate="safhApp.internacoesDetalhes.posologias">Posologias</span></dt>
        <dd>
          <div *ngIf="internacoesDetalhes.posologias">
            <a [routerLink]="['/posologias', internacoesDetalhes.posologias?.id, 'view']">{{
              internacoesDetalhes.posologias?.posologia
            }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/internacoes-detalhes', internacoesDetalhes.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>

// src/main/webapp/app/entities/internacoes-detalhes/internacoes-detalhes-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, ICrudGetAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './internacoes-detalhes.reducer';
import { IInternacoesDetalhes } from 'app/shared/model/internacoes-detalhes.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IInternacoesDetalhesDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class InternacoesDetalhesDetail extends React.Component<IInternacoesDetalhesDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { internacoesDetalhesEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="safhApp.internacoesDetalhes.detail.title">InternacoesDetalhes</Translate> [
            <b>{internacoesDetalhesEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="dataDetalhe">
                <Translate contentKey="safhApp.internacoesDetalhes.dataDetalhe">Data Detalhe</Translate>
              </span>
            </dt>
            <dd>
              <TextFormat value={internacoesDetalhesEntity.dataDetalhe} type="date" format={APP_LOCAL_DATE_FORMAT} />
            </dd>
            <dt>
              <span id="horario">
                <Translate contentKey="safhApp.internacoesDetalhes.horario">Horario</Translate>
              </span>
            </dt>
            <dd>
              <TextFormat value={internacoesDetalhesEntity.horario} type="date" format={APP_LOCAL_DATE_FORMAT} />
            </dd>
            <dt>
              <span id="qtd">
                <Translate contentKey="safhApp.internacoesDetalhes.qtd">Qtd</Translate>
              </span>
            </dt>
            <dd>{internacoesDetalhesEntity.qtd}</dd>
            <dt>
              <Translate contentKey="safhApp.internacoesDetalhes.internacoes">Internacoes</Translate>
            </dt>
            <dd>{internacoesDetalhesEntity.internacoes ? internacoesDetalhesEntity.internacoes.descricao : ''}</dd>
            <dt>
              <Translate contentKey="safhApp.internacoesDetalhes.dietas">Dietas</Translate>
            </dt>
            <dd>{internacoesDetalhesEntity.dietas ? internacoesDetalhesEntity.dietas.dieta : ''}</dd>
            <dt>
              <Translate contentKey="safhApp.internacoesDetalhes.prescricoes">Prescricoes</Translate>
            </dt>
            <dd>{internacoesDetalhesEntity.prescricoes ? internacoesDetalhesEntity.prescricoes.prescricao : ''}</dd>
            <dt>
              <Translate contentKey="safhApp.internacoesDetalhes.posologias">Posologias</Translate>
            </dt>
            <dd>{internacoesDetalhesEntity.posologias ? internacoesDetalhesEntity.posologias.posologia : ''}</dd>
          </dl>
          <Button tag={Link} to="/internacoes-detalhes" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/internacoes-detalhes/${internacoesDetalhesEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ internacoesDetalhes }: IRootState) => ({
  internacoesDetalhesEntity: internacoesDetalhes.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(InternacoesDetalhesDetail);
