// src/main/webapp/app/entities/medicos/medicos.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudSearchAction, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities } from './medicos.reducer';
import { IMedicos } from 'app/shared/model/medicos.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IMedicosProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export interface IMedicosState {
  search: string;
}

export class Medicos extends React.Component<IMedicosProps, IMedicosState> {
  state: IMedicosState = {
    search: ''
  };

  componentDidMount() {
    this.props.getEntities();
  }

  search = () => {
    if (this.state.search) {
      this.props.getSearchEntities(this.state.search);
    }
  };

  clear = () => {
    this.setState({ search: '' }, () => {
      this.props.getEntities();
    });
  };

  handleSearch = event => this.setState({ search: event.target.value });

  render() {
    const { medicosList, match } = this.props;
    return (
      <div>
        <h2 id="medicos-heading">
          <Translate contentKey="safhApp.medicos.home.title">Medicos</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="safhApp.medicos.home.createLabel">Create a new Medicos</Translate>
          </Link>
        </h2>
        <Row>
          <Col sm="12">
            <AvForm onSubmit={this.search}>
              <AvGroup>
                <InputGroup>
                  <AvInput
                    type="text"
                    name="search"
                    value={this.state.search}
                    onChange={this.handleSearch}
                    placeholder={translate('safhApp.medicos.home.search')}
                  />
                  <Button className="input-group-addon">
                    <FontAwesomeIcon icon="search" />
                  </Button>
                  <Button type="reset" className="input-group-addon" onClick={this.clear}>
                    <FontAwesomeIcon icon="trash" />
                  </Button>
                </InputGroup>
              </AvGroup>
            </AvForm>
          </Col>
        </Row>
        <div className="table-responsive">
          {medicosList && medicosList.length > 0 ? (
            <Table responsive aria-describedby="medicos-heading">
              <thead>
                <tr>
                  <th>
                    <Translate contentKey="global.field.id">ID</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.nome">Nome</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.crm">Crm</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.cpf">Cpf</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.email">Email</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.cep">Cep</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.logradouro">Logradouro</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.numero">Numero</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.complemento">Complemento</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.bairro">Bairro</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.cidade">Cidade</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.uF">U F</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.especialidades">Especialidades</Translate>
                  </th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {medicosList.map((medicos, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${medicos.id}`} color="link" size="sm">
                        {medicos.id}
                      </Button>
                    </td>
                    <td>{medicos.nome}</td>
                    <td>{medicos.crm}</td>
                    <td>{medicos.cpf}</td>
                    <td>{medicos.email}</td>
                    <td>{medicos.cep}</td>
                    <td>{medicos.logradouro}</td>
                    <td>{medicos.numero}</td>
                    <td>{medicos.complemento}</td>
                    <td>{medicos.bairro}</td>
                    <td>{medicos.cidade}</td>
                    <td>
                      <Translate contentKey={`safhApp.Estados.${medicos.uF}`} />
                    </td>
                    <td>
                      {medicos.especialidades ? (
                        <Link to={`especialidades/${medicos.especialidades.id}`}>{medicos.especialidades.especialidade}</Link>
                      ) : (
                        ''
                      )}
                    </td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${medicos.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.view">View</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${medicos.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.edit">Edit</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${medicos.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.delete">Delete</Translate>
                          </span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            <div className="alert alert-warning">
              <Translate contentKey="safhApp.medicos.home.notFound">No Medicos found</Translate>
            </div>
          )}
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ medicos }: IRootState) => ({
  medicosList: medicos.entities
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Medicos);

// src/main/webapp/app/entities/medicos/list/medicos.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IMedicos } from '../medicos.model';
import { MedicosService } from '../service/medicos.service';
import { MedicosDeleteDialogComponent } from '../delete/medicos-delete-dialog.component';

@Component({
  selector: 'jhi-medicos',
  templateUrl: './medicos.component.html',
})
export class MedicosComponent implements OnInit {
  medicos?: IMedicos[];
  isLoading = false;

  constructor(protected medicosService: MedicosService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.medicosService.query().subscribe(
      (res: HttpResponse<IMedicos[]>) => {
        this.isLoading = false;
        this.medicos = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IMedicos): number {
    return item.id!;
  }

  delete(medicos: IMedicos): void {
    const modalRef = this.modalService.open(MedicosDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.medicos = medicos;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="MedicosHeading">
    <span jhiTranslate="safhApp.medicos.home.title">Medicos</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="safhApp.medicos.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-medicos"
        [routerLink]="['/medicos/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="safhApp.medicos.home.createLabel"> Create a new Medicos </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="medicos?.length === 0">
    <span jhiTranslate="safhApp.medicos.home.notFound">No medicos found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="medicos && medicos.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="safhApp.medicos.nome">Nome</span></th>
          <th scope="col"><span jhiTranslate="safhApp.medicos.crm">Crm</span></th>
          <th scope="col"><span jhiTranslate="safhApp.medicos.cpf">Cpf</span></th>
          <th scope="col"><span jhiTranslate="safhApp.medicos.email">Email</span></th>
          <th scope="col"><span jhiTranslate="safhApp.medicos.cep">Cep</span></th>
          <th scope="col"><span jhiTranslate="safhApp.medicos.logradouro">Logradouro</span></th>
          <th scope="col"><span jhiTranslate="safhApp.medicos.numero">Numero</span></th>
          <th scope="col"><span jhiTranslate="safhApp.medicos.complemento">Complemento</span></th>
          <th scope="col"><span jhiTranslate="safhApp.medicos.bairro">Bairro</span></th>
          <th scope="col"><span jhiTranslate="safhApp.medicos.cidade">Cidade</span></th>
          <th scope="col"><span jhiTranslate="safhApp.medicos.uF">U F</span></th>
          <th scope="col"><span jhiTranslate="safhApp.medicos.especialidades">Especialidades</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let medicos of medicos; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/medicos', medicos.id, 'view']">{{ medicos.id }}</a>
          </td>
          <td>{{ medicos.nome }}</td>
          <td>{{ medicos.crm }}</td>
          <td>{{ medicos.cpf }}</td>
          <td>{{ medicos.email }}</td>
          <td>{{ medicos.cep }}</td>
          <td>{{ medicos.logradouro }}</td>
          <td>{{ medicos.numero }}</td>
          <td>{{ medicos.complemento }}</td>
          <td>{{ medicos.bairro }}</td>
          <td>{{ medicos.cidade }}</td>
          <td jhiTranslate="{{ 'safhApp.Estados.' + medicos.uF }}">{{ medicos.uF }}</td>
          <td>
            <div *ngIf="medicos.especialidades">
              <a [routerLink]="['/especialidades', medicos.especialidades?.id, 'view']">{{ medicos.especialidades?.especialidade }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/medicos', medicos.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/medicos', medicos.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(medicos)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
