// src/main/webapp/app/entities/leitos/leitos.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudSearchAction, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities } from './leitos.reducer';
import { ILeitos } from 'app/shared/model/leitos.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ILeitosProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export interface ILeitosState {
  search: string;
}

export class Leitos extends React.Component<ILeitosProps, ILeitosState> {
  state: ILeitosState = {
    search: ''
  };

  componentDidMount() {
    this.props.getEntities();
  }

  search = () => {
    if (this.state.search) {
      this.props.getSearchEntities(this.state.search);
    }
  };

  clear = () => {
    this.setState({ search: '' }, () => {
      this.props.getEntities();
    });
  };

  handleSearch = event => this.setState({ search: event.target.value });

  render() {
    const { leitosList, match } = this.props;
    return (
      <div>
        <h2 id="leitos-heading">
          <Translate contentKey="safhApp.leitos.home.title">Leitos</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="safhApp.leitos.home.createLabel">Create a new Leitos</Translate>
          </Link>
        </h2>
        <Row>
          <Col sm="12">
            <AvForm onSubmit={this.search}>
              <AvGroup>
                <InputGroup>
                  <AvInput
                    type="text"
                    name="search"
                    value={this.state.search}
                    onChange={this.handleSearch}
                    placeholder={translate('safhApp.leitos.home.search')}
                  />
                  <Button className="input-group-addon">
                    <FontAwesomeIcon icon="search" />
                  </Button>
                  <Button type="reset" className="input-group-addon" onClick={this.clear}>
                    <FontAwesomeIcon icon="trash" />
                  </Button>
                </InputGroup>
              </AvGroup>
            </AvForm>
          </Col>
        </Row>
        <div className="table-responsive">
          {leitosList && leitosList.length > 0 ? (
            <Table responsive aria-describedby="leitos-heading">
              <thead>
                <tr>
                  <th>
                    <Translate contentKey="global.field.id">ID</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.leitos.leito">Leito</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.leitos.tipo">Tipo</Translate>
                  </th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {leitosList.map((leitos, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${leitos.id}`} color="link" size="sm">
                        {leitos.id}
                      </Button>
                    </td>
                    <td>{leitos.leito}</td>
                    <td>{leitos.tipo}</td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${leitos.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.view">View</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${leitos.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.edit">Edit</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${leitos.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.delete">Delete</Translate>
                          </span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            <div className="alert alert-warning">
              <Translate contentKey="safhApp.leitos.home.notFound">No Leitos found</Translate>
            </div>
          )}
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ leitos }: IRootState) => ({
  leitosList: leitos.entities
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Leitos);

// src/main/webapp/app/entities/leitos/list/leitos.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ILeitos } from '../leitos.model';
import { LeitosService } from '../service/leitos.service';
import { LeitosDeleteDialogComponent } from '../delete/leitos-delete-dialog.component';

@Component({
  selector: 'jhi-leitos',
  templateUrl: './leitos.component.html',
})
export class LeitosComponent implements OnInit {
  leitos?: ILeitos[];
  isLoading = false;

  constructor(protected leitosService: LeitosService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.leitosService.query().subscribe(
      (res: HttpResponse<ILeitos[]>) => {
        this.isLoading = false;
        this.leitos = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: ILeitos): number {
    return item.id!;
  }

  delete(leitos: ILeitos): void {
    const modalRef = this.modalService.open(LeitosDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.leitos = leitos;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="LeitosHeading">
    <span jhiTranslate="safhApp.leitos.home.title">Leitos</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="safhApp.leitos.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-leitos"
        [routerLink]="['/leitos/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="safhApp.leitos.home.createLabel"> Create a new Leitos </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="leitos?.length === 0">
    <span jhiTranslate="safhApp.leitos.home.notFound">No leitos found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="leitos && leitos.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="safhApp.leitos.leito">Leito</span></th>
          <th scope="col"><span jhiTranslate="safhApp.leitos.tipo">Tipo</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let leitos of leitos; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/leitos', leitos.id, 'view']">{{ leitos.id }}</a>
          </td>
          <td>{{ leitos.leito }}</td>
          <td>{{ leitos.tipo }}</td>
          <td class="text-right">
            <div class="btn-group">
              <button type="submit" [routerLink]="['/leitos', leitos.id, 'view']" class="btn btn-info btn-sm" data-cy="entityDetailsButton">
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button type="submit" [routerLink]="['/leitos', leitos.id, 'edit']" class="btn btn-primary btn-sm" data-cy="entityEditButton">
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(leitos)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
