// src/main/webapp/app/entities/dietas/detail/dietas-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IDietas } from '../dietas.model';

@Component({
  selector: 'jhi-dietas-detail',
  templateUrl: './dietas-detail.component.html',
})
export class DietasDetailComponent implements OnInit {
  dietas: IDietas | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ dietas }) => {
      this.dietas = dietas;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <div *ngIf="dietas">
      <h2 data-cy="dietasDetailsHeading"><span jhiTranslate="safhApp.dietas.detail.title">Dietas</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ dietas.id }}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.dietas.dieta">Dieta</span></dt>
        <dd>
          <span>{{ dietas.dieta }}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.dietas.descricao">Descricao</span></dt>
        <dd>
          <span>{{ dietas.descricao }}</span>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/dietas', dietas.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>

// src/main/webapp/app/entities/dietas/dietas-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './dietas.reducer';
import { IDietas } from 'app/shared/model/dietas.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IDietasDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class DietasDetail extends React.Component<IDietasDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { dietasEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="safhApp.dietas.detail.title">Dietas</Translate> [<b>{dietasEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="dieta">
                <Translate contentKey="safhApp.dietas.dieta">Dieta</Translate>
              </span>
            </dt>
            <dd>{dietasEntity.dieta}</dd>
            <dt>
              <span id="descricao">
                <Translate contentKey="safhApp.dietas.descricao">Descricao</Translate>
              </span>
            </dt>
            <dd>{dietasEntity.descricao}</dd>
          </dl>
          <Button tag={Link} to="/dietas" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/dietas/${dietasEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ dietas }: IRootState) => ({
  dietasEntity: dietas.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(DietasDetail);
