// src/main/webapp/app/entities/dietas/list/dietas.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IDietas } from '../dietas.model';
import { DietasService } from '../service/dietas.service';
import { DietasDeleteDialogComponent } from '../delete/dietas-delete-dialog.component';

@Component({
  selector: 'jhi-dietas',
  templateUrl: './dietas.component.html',
})
export class DietasComponent implements OnInit {
  dietas?: IDietas[];
  isLoading = false;

  constructor(protected dietasService: DietasService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.dietasService.query().subscribe(
      (res: HttpResponse<IDietas[]>) => {
        this.isLoading = false;
        this.dietas = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IDietas): number {
    return item.id!;
  }

  delete(dietas: IDietas): void {
    const modalRef = this.modalService.open(DietasDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.dietas = dietas;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="DietasHeading">
    <span jhiTranslate="safhApp.dietas.home.title">Dietas</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="safhApp.dietas.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-dietas"
        [routerLink]="['/dietas/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="safhApp.dietas.home.createLabel"> Create a new Dietas </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="dietas?.length === 0">
    <span jhiTranslate="safhApp.dietas.home.notFound">No dietas found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="dietas && dietas.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="safhApp.dietas.dieta">Dieta</span></th>
          <th scope="col"><span jhiTranslate="safhApp.dietas.descricao">Descricao</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let dietas of dietas; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/dietas', dietas.id, 'view']">{{ dietas.id }}</a>
          </td>
          <td>{{ dietas.dieta }}</td>
          <td>{{ dietas.descricao }}</td>
          <td class="text-right">
            <div class="btn-group">
              <button type="submit" [routerLink]="['/dietas', dietas.id, 'view']" class="btn btn-info btn-sm" data-cy="entityDetailsButton">
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button type="submit" [routerLink]="['/dietas', dietas.id, 'edit']" class="btn btn-primary btn-sm" data-cy="entityEditButton">
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(dietas)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/dietas/dietas.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudSearchAction, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities } from './dietas.reducer';
import { IDietas } from 'app/shared/model/dietas.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IDietasProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export interface IDietasState {
  search: string;
}

export class Dietas extends React.Component<IDietasProps, IDietasState> {
  state: IDietasState = {
    search: ''
  };

  componentDidMount() {
    this.props.getEntities();
  }

  search = () => {
    if (this.state.search) {
      this.props.getSearchEntities(this.state.search);
    }
  };

  clear = () => {
    this.setState({ search: '' }, () => {
      this.props.getEntities();
    });
  };

  handleSearch = event => this.setState({ search: event.target.value });

  render() {
    const { dietasList, match } = this.props;
    return (
      <div>
        <h2 id="dietas-heading">
          <Translate contentKey="safhApp.dietas.home.title">Dietas</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="safhApp.dietas.home.createLabel">Create a new Dietas</Translate>
          </Link>
        </h2>
        <Row>
          <Col sm="12">
            <AvForm onSubmit={this.search}>
              <AvGroup>
                <InputGroup>
                  <AvInput
                    type="text"
                    name="search"
                    value={this.state.search}
                    onChange={this.handleSearch}
                    placeholder={translate('safhApp.dietas.home.search')}
                  />
                  <Button className="input-group-addon">
                    <FontAwesomeIcon icon="search" />
                  </Button>
                  <Button type="reset" className="input-group-addon" onClick={this.clear}>
                    <FontAwesomeIcon icon="trash" />
                  </Button>
                </InputGroup>
              </AvGroup>
            </AvForm>
          </Col>
        </Row>
        <div className="table-responsive">
          {dietasList && dietasList.length > 0 ? (
            <Table responsive aria-describedby="dietas-heading">
              <thead>
                <tr>
                  <th>
                    <Translate contentKey="global.field.id">ID</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.dietas.dieta">Dieta</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.dietas.descricao">Descricao</Translate>
                  </th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {dietasList.map((dietas, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${dietas.id}`} color="link" size="sm">
                        {dietas.id}
                      </Button>
                    </td>
                    <td>{dietas.dieta}</td>
                    <td>{dietas.descricao}</td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${dietas.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.view">View</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${dietas.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.edit">Edit</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${dietas.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.delete">Delete</Translate>
                          </span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            <div className="alert alert-warning">
              <Translate contentKey="safhApp.dietas.home.notFound">No Dietas found</Translate>
            </div>
          )}
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ dietas }: IRootState) => ({
  dietasList: dietas.entities
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Dietas);
