// src/main/webapp/app/entities/internacoes-detalhes/internacoes-detalhes.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudSearchAction, ICrudGetAllAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities } from './internacoes-detalhes.reducer';
import { IInternacoesDetalhes } from 'app/shared/model/internacoes-detalhes.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IInternacoesDetalhesProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export interface IInternacoesDetalhesState {
  search: string;
}

export class InternacoesDetalhes extends React.Component<IInternacoesDetalhesProps, IInternacoesDetalhesState> {
  state: IInternacoesDetalhesState = {
    search: ''
  };

  componentDidMount() {
    this.props.getEntities();
  }

  search = () => {
    if (this.state.search) {
      this.props.getSearchEntities(this.state.search);
    }
  };

  clear = () => {
    this.setState({ search: '' }, () => {
      this.props.getEntities();
    });
  };

  handleSearch = event => this.setState({ search: event.target.value });

  render() {
    const { internacoesDetalhesList, match } = this.props;
    return (
      <div>
        <h2 id="internacoes-detalhes-heading">
          <Translate contentKey="safhApp.internacoesDetalhes.home.title">Internacoes Detalhes</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="safhApp.internacoesDetalhes.home.createLabel">Create a new Internacoes Detalhes</Translate>
          </Link>
        </h2>
        <Row>
          <Col sm="12">
            <AvForm onSubmit={this.search}>
              <AvGroup>
                <InputGroup>
                  <AvInput
                    type="text"
                    name="search"
                    value={this.state.search}
                    onChange={this.handleSearch}
                    placeholder={translate('safhApp.internacoesDetalhes.home.search')}
                  />
                  <Button className="input-group-addon">
                    <FontAwesomeIcon icon="search" />
                  </Button>
                  <Button type="reset" className="input-group-addon" onClick={this.clear}>
                    <FontAwesomeIcon icon="trash" />
                  </Button>
                </InputGroup>
              </AvGroup>
            </AvForm>
          </Col>
        </Row>
        <div className="table-responsive">
          {internacoesDetalhesList && internacoesDetalhesList.length > 0 ? (
            <Table responsive aria-describedby="internacoes-detalhes-heading">
              <thead>
                <tr>
                  <th>
                    <Translate contentKey="global.field.id">ID</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoesDetalhes.dataDetalhe">Data Detalhe</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoesDetalhes.horario">Horario</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoesDetalhes.qtd">Qtd</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoesDetalhes.internacoes">Internacoes</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoesDetalhes.dietas">Dietas</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoesDetalhes.prescricoes">Prescricoes</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoesDetalhes.posologias">Posologias</Translate>
                  </th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {internacoesDetalhesList.map((internacoesDetalhes, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${internacoesDetalhes.id}`} color="link" size="sm">
                        {internacoesDetalhes.id}
                      </Button>
                    </td>
                    <td>
                      <TextFormat type="date" value={internacoesDetalhes.dataDetalhe} format={APP_LOCAL_DATE_FORMAT} />
                    </td>
                    <td>
                      <TextFormat type="date" value={internacoesDetalhes.horario} format={APP_LOCAL_DATE_FORMAT} />
                    </td>
                    <td>{internacoesDetalhes.qtd}</td>
                    <td>
                      {internacoesDetalhes.internacoes ? (
                        <Link to={`internacoes/${internacoesDetalhes.internacoes.id}`}>{internacoesDetalhes.internacoes.descricao}</Link>
                      ) : (
                        ''
                      )}
                    </td>
                    <td>
                      {internacoesDetalhes.dietas ? (
                        <Link to={`dietas/${internacoesDetalhes.dietas.id}`}>{internacoesDetalhes.dietas.dieta}</Link>
                      ) : (
                        ''
                      )}
                    </td>
                    <td>
                      {internacoesDetalhes.prescricoes ? (
                        <Link to={`prescricoes/${internacoesDetalhes.prescricoes.id}`}>{internacoesDetalhes.prescricoes.prescricao}</Link>
                      ) : (
                        ''
                      )}
                    </td>
                    <td>
                      {internacoesDetalhes.posologias ? (
                        <Link to={`posologias/${internacoesDetalhes.posologias.id}`}>{internacoesDetalhes.posologias.posologia}</Link>
                      ) : (
                        ''
                      )}
                    </td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${internacoesDetalhes.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.view">View</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${internacoesDetalhes.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.edit">Edit</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${internacoesDetalhes.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.delete">Delete</Translate>
                          </span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            <div className="alert alert-warning">
              <Translate contentKey="safhApp.internacoesDetalhes.home.notFound">No Internacoes Detalhes found</Translate>
            </div>
          )}
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ internacoesDetalhes }: IRootState) => ({
  internacoesDetalhesList: internacoesDetalhes.entities
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(InternacoesDetalhes);

// src/main/webapp/app/entities/internacoes-detalhes/list/internacoes-detalhes.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IInternacoesDetalhes } from '../internacoes-detalhes.model';
import { InternacoesDetalhesService } from '../service/internacoes-detalhes.service';
import { InternacoesDetalhesDeleteDialogComponent } from '../delete/internacoes-detalhes-delete-dialog.component';

@Component({
  selector: 'jhi-internacoes-detalhes',
  templateUrl: './internacoes-detalhes.component.html',
})
export class InternacoesDetalhesComponent implements OnInit {
  internacoesDetalhes?: IInternacoesDetalhes[];
  isLoading = false;

  constructor(protected internacoesDetalhesService: InternacoesDetalhesService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.internacoesDetalhesService.query().subscribe(
      (res: HttpResponse<IInternacoesDetalhes[]>) => {
        this.isLoading = false;
        this.internacoesDetalhes = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IInternacoesDetalhes): number {
    return item.id!;
  }

  delete(internacoesDetalhes: IInternacoesDetalhes): void {
    const modalRef = this.modalService.open(InternacoesDetalhesDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.internacoesDetalhes = internacoesDetalhes;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="InternacoesDetalhesHeading">
    <span jhiTranslate="safhApp.internacoesDetalhes.home.title">Internacoes Detalhes</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="safhApp.internacoesDetalhes.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-internacoes-detalhes"
        [routerLink]="['/internacoes-detalhes/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="safhApp.internacoesDetalhes.home.createLabel"> Create a new Internacoes Detalhes </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="internacoesDetalhes?.length === 0">
    <span jhiTranslate="safhApp.internacoesDetalhes.home.notFound">No internacoesDetalhes found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="internacoesDetalhes && internacoesDetalhes.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="safhApp.internacoesDetalhes.dataDetalhe">Data Detalhe</span></th>
          <th scope="col"><span jhiTranslate="safhApp.internacoesDetalhes.horario">Horario</span></th>
          <th scope="col"><span jhiTranslate="safhApp.internacoesDetalhes.qtd">Qtd</span></th>
          <th scope="col"><span jhiTranslate="safhApp.internacoesDetalhes.internacoes">Internacoes</span></th>
          <th scope="col"><span jhiTranslate="safhApp.internacoesDetalhes.dietas">Dietas</span></th>
          <th scope="col"><span jhiTranslate="safhApp.internacoesDetalhes.prescricoes">Prescricoes</span></th>
          <th scope="col"><span jhiTranslate="safhApp.internacoesDetalhes.posologias">Posologias</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let internacoesDetalhes of internacoesDetalhes; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/internacoes-detalhes', internacoesDetalhes.id, 'view']">{{ internacoesDetalhes.id }}</a>
          </td>
          <td>{{ internacoesDetalhes.dataDetalhe | formatMediumDate }}</td>
          <td>{{ internacoesDetalhes.horario | formatMediumDate }}</td>
          <td>{{ internacoesDetalhes.qtd }}</td>
          <td>
            <div *ngIf="internacoesDetalhes.internacoes">
              <a [routerLink]="['/internacoes', internacoesDetalhes.internacoes?.id, 'view']">{{
                internacoesDetalhes.internacoes?.descricao
              }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="internacoesDetalhes.dietas">
              <a [routerLink]="['/dietas', internacoesDetalhes.dietas?.id, 'view']">{{ internacoesDetalhes.dietas?.dieta }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="internacoesDetalhes.prescricoes">
              <a [routerLink]="['/prescricoes', internacoesDetalhes.prescricoes?.id, 'view']">{{
                internacoesDetalhes.prescricoes?.prescricao
              }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="internacoesDetalhes.posologias">
              <a [routerLink]="['/posologias', internacoesDetalhes.posologias?.id, 'view']">{{
                internacoesDetalhes.posologias?.posologia
              }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/internacoes-detalhes', internacoesDetalhes.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/internacoes-detalhes', internacoesDetalhes.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(internacoesDetalhes)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
