// src/main/webapp/app/entities/medicamentos/medicamentos.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs/Rx';
import { JhiEventManager, JhiParseLinks, JhiAlertService } from 'ng-jhipster';

import { Medicamentos } from './medicamentos.model';
import { MedicamentosService } from './medicamentos.service';
import { ITEMS_PER_PAGE, Principal, ResponseWrapper } from '../../shared';

@Component({
    selector: 'jhi-medicamentos',
    templateUrl: './medicamentos.component.html'
})
export class MedicamentosComponent implements OnInit, OnDestroy {

    medicamentos: Medicamentos[];
    currentAccount: any;
    eventSubscriber: Subscription;
    itemsPerPage: number;
    links: any;
    page: any;
    predicate: any;
    queryCount: any;
    reverse: any;
    totalItems: number;
    currentSearch: string;

    constructor(
        private medicamentosService: MedicamentosService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private parseLinks: JhiParseLinks,
        private activatedRoute: ActivatedRoute,
        private principal: Principal
    ) {
        this.medicamentos = [];
        this.itemsPerPage = ITEMS_PER_PAGE;
        this.page = 0;
        this.links = {
            last: 0
        };
        this.predicate = 'id';
        this.reverse = true;
        this.currentSearch = activatedRoute.snapshot.params['search'] ? activatedRoute.snapshot.params['search'] : '';
    }

    loadAll() {
        if (this.currentSearch) {
            this.medicamentosService.search({
                query: this.currentSearch,
                page: this.page,
                size: this.itemsPerPage,
                sort: this.sort()
            }).subscribe(
                (res: ResponseWrapper) => this.onSuccess(res.json, res.headers),
                (res: ResponseWrapper) => this.onError(res.json)
            );
            return;
        }
        this.medicamentosService.query({
            page: this.page,
            size: this.itemsPerPage,
            sort: this.sort()
        }).subscribe(
            (res: ResponseWrapper) => this.onSuccess(res.json, res.headers),
            (res: ResponseWrapper) => this.onError(res.json)
        );
    }

    reset() {
        this.page = 0;
        this.medicamentos = [];
        this.loadAll();
    }

    loadPage(page) {
        this.page = page;
        this.loadAll();
    }

    clear() {
        this.medicamentos = [];
        this.links = {
            last: 0
        };
        this.page = 0;
        this.predicate = 'id';
        this.reverse = true;
        this.currentSearch = '';
        this.loadAll();
    }

    search(query) {
        if (!query) {
            return this.clear();
        }
        this.medicamentos = [];
        this.links = {
            last: 0
        };
        this.page = 0;
        this.predicate = '_score';
        this.reverse = false;
        this.currentSearch = query;
        this.loadAll();
    }
    ngOnInit() {
        this.loadAll();
        this.principal.identity().then((account) => {
            this.currentAccount = account;
        });
        this.registerChangeInMedicamentos();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: Medicamentos) {
        return item.id;
    }
    registerChangeInMedicamentos() {
        this.eventSubscriber = this.eventManager.subscribe('medicamentosListModification', (response) => this.reset());
    }

    sort() {
        const result = [this.predicate + ',' + (this.reverse ? 'asc' : 'desc')];
        if (this.predicate !== 'id') {
            result.push('id');
        }
        return result;
    }

    private onSuccess(data, headers) {
        this.links = this.parseLinks.parse(headers.get('link'));
        this.totalItems = headers.get('X-Total-Count');
        for (let i = 0; i < data.length; i++) {
            this.medicamentos.push(data[i]);
        }
    }

    private onError(error) {
        this.jhiAlertService.error(error.message, null, null);
    }
}

<div>
    <h2>
        <span jhiTranslate="safhApp.medicamentos.home.title">Medicamentos</span>
        <button class="btn btn-primary float-right jh-create-entity create-medicamentos" [routerLink]="['/', { outlets: { popup: ['medicamentos-new'] } }]">
            <span class="fa fa-plus"></span>
            <span class="hidden-sm-down"  jhiTranslate="safhApp.medicamentos.home.createLabel">
            Create new Medicamentos
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <div class="row">
        <div class="col-sm-12">
            <form name="searchForm" class="form-inline">
                <div class="input-group w-100 mt-3">
                    <input type="text" class="form-control" [(ngModel)]="currentSearch" id="currentSearch" name="currentSearch" placeholder="{{ 'safhApp.medicamentos.home.search' | translate }}">
                    <button class="input-group-addon btn btn-info" (click)="search(currentSearch)">
                        <span class="fa fa-search"></span>
                    </button>
                    <button class="input-group-addon btn btn-danger" (click)="clear()" *ngIf="currentSearch">
                        <span class="fa fa-trash-o"></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <br/>
    <div class="table-responsive" *ngIf="medicamentos">
        <table class="table table-striped">
            <thead>
            <tr jhiSort [(predicate)]="predicate" [(ascending)]="reverse" [callback]="reset.bind(this)">
            <th jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="descricao"><span jhiTranslate="safhApp.medicamentos.descricao">Descricao</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="registroMinisterioSaude"><span jhiTranslate="safhApp.medicamentos.registroMinisterioSaude">Registro Ministerio Saude</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="codigoBarras"><span jhiTranslate="safhApp.medicamentos.codigoBarras">Codigo Barras</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="qtdAtual"><span jhiTranslate="safhApp.medicamentos.qtdAtual">Qtd Atual</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="qtdMin"><span jhiTranslate="safhApp.medicamentos.qtdMin">Qtd Min</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="qtdMax"><span jhiTranslate="safhApp.medicamentos.qtdMax">Qtd Max</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="observacoes"><span jhiTranslate="safhApp.medicamentos.observacoes">Observacoes</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="apresentacao"><span jhiTranslate="safhApp.medicamentos.apresentacao">Apresentacao</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="posologiaPadrao.posologia"><span jhiTranslate="safhApp.medicamentos.posologiaPadrao">Posologia Padrao</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="fabricantes.fabricante"><span jhiTranslate="safhApp.medicamentos.fabricantes">Fabricantes</span> <span class="fa fa-sort"></span></th>
            <th></th>
            </tr>
            </thead>
            <tbody infinite-scroll (scrolled)="loadPage(page + 1)" [infiniteScrollDisabled]="page >= links['last']" [infiniteScrollDistance]="0">
            <tr *ngFor="let medicamentos of medicamentos ;trackBy: trackId">
                <td><a [routerLink]="['../medicamentos', medicamentos.id ]">{{medicamentos.id}}</a></td>
                <td>{{medicamentos.descricao}}</td>
                <td>{{medicamentos.registroMinisterioSaude}}</td>
                <td>{{medicamentos.codigoBarras}}</td>
                <td>{{medicamentos.qtdAtual}}</td>
                <td>{{medicamentos.qtdMin}}</td>
                <td>{{medicamentos.qtdMax}}</td>
                <td>{{medicamentos.observacoes}}</td>
                <td>{{medicamentos.apresentacao}}</td>
                <td>
                    <div *ngIf="medicamentos.posologiaPadrao">
                        <a [routerLink]="['../posologias', medicamentos.posologiaPadrao?.id ]" >{{medicamentos.posologiaPadrao?.posologia}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="medicamentos.fabricantes">
                        <a [routerLink]="['../fabricantes', medicamentos.fabricantes?.id ]" >{{medicamentos.fabricantes?.fabricante}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['../medicamentos', medicamentos.id ]"
                                class="btn btn-info btn-sm">
                            <span class="fa fa-eye"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'medicamentos/'+ medicamentos.id + '/edit'} }]"
                                replaceUrl="true"
                                class="btn btn-primary btn-sm">
                            <span class="fa fa-pencil"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'medicamentos/'+ medicamentos.id + '/delete'} }]"
                                replaceUrl="true"
                                class="btn btn-danger btn-sm">
                            <span class="fa fa-remove"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/medicamentos/medicamentos.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudSearchAction, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities } from './medicamentos.reducer';
import { IMedicamentos } from 'app/shared/model/medicamentos.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IMedicamentosProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export interface IMedicamentosState {
  search: string;
}

export class Medicamentos extends React.Component<IMedicamentosProps, IMedicamentosState> {
  state: IMedicamentosState = {
    search: ''
  };

  componentDidMount() {
    this.props.getEntities();
  }

  search = () => {
    if (this.state.search) {
      this.props.getSearchEntities(this.state.search);
    }
  };

  clear = () => {
    this.setState({ search: '' }, () => {
      this.props.getEntities();
    });
  };

  handleSearch = event => this.setState({ search: event.target.value });

  render() {
    const { medicamentosList, match } = this.props;
    return (
      <div>
        <h2 id="medicamentos-heading">
          <Translate contentKey="safhApp.medicamentos.home.title">Medicamentos</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="safhApp.medicamentos.home.createLabel">Create a new Medicamentos</Translate>
          </Link>
        </h2>
        <Row>
          <Col sm="12">
            <AvForm onSubmit={this.search}>
              <AvGroup>
                <InputGroup>
                  <AvInput
                    type="text"
                    name="search"
                    value={this.state.search}
                    onChange={this.handleSearch}
                    placeholder={translate('safhApp.medicamentos.home.search')}
                  />
                  <Button className="input-group-addon">
                    <FontAwesomeIcon icon="search" />
                  </Button>
                  <Button type="reset" className="input-group-addon" onClick={this.clear}>
                    <FontAwesomeIcon icon="trash" />
                  </Button>
                </InputGroup>
              </AvGroup>
            </AvForm>
          </Col>
        </Row>
        <div className="table-responsive">
          {medicamentosList && medicamentosList.length > 0 ? (
            <Table responsive aria-describedby="medicamentos-heading">
              <thead>
                <tr>
                  <th>
                    <Translate contentKey="global.field.id">ID</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicamentos.descricao">Descricao</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicamentos.registroMinisterioSaude">Registro Ministerio Saude</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicamentos.codigoBarras">Codigo Barras</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicamentos.qtdAtual">Qtd Atual</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicamentos.qtdMin">Qtd Min</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicamentos.qtdMax">Qtd Max</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicamentos.observacoes">Observacoes</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicamentos.apresentacao">Apresentacao</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicamentos.posologiaPadrao">Posologia Padrao</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicamentos.fabricantes">Fabricantes</Translate>
                  </th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {medicamentosList.map((medicamentos, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${medicamentos.id}`} color="link" size="sm">
                        {medicamentos.id}
                      </Button>
                    </td>
                    <td>{medicamentos.descricao}</td>
                    <td>{medicamentos.registroMinisterioSaude}</td>
                    <td>{medicamentos.codigoBarras}</td>
                    <td>{medicamentos.qtdAtual}</td>
                    <td>{medicamentos.qtdMin}</td>
                    <td>{medicamentos.qtdMax}</td>
                    <td>{medicamentos.observacoes}</td>
                    <td>{medicamentos.apresentacao}</td>
                    <td>
                      {medicamentos.posologiaPadrao ? (
                        <Link to={`posologias/${medicamentos.posologiaPadrao.id}`}>{medicamentos.posologiaPadrao.posologia}</Link>
                      ) : (
                        ''
                      )}
                    </td>
                    <td>
                      {medicamentos.fabricantes ? (
                        <Link to={`fabricantes/${medicamentos.fabricantes.id}`}>{medicamentos.fabricantes.fabricante}</Link>
                      ) : (
                        ''
                      )}
                    </td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${medicamentos.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.view">View</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${medicamentos.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.edit">Edit</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${medicamentos.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.delete">Delete</Translate>
                          </span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            <div className="alert alert-warning">
              <Translate contentKey="safhApp.medicamentos.home.notFound">No Medicamentos found</Translate>
            </div>
          )}
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ medicamentos }: IRootState) => ({
  medicamentosList: medicamentos.entities
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Medicamentos);
