// src/main/webapp/app/entities/medicamentos/detail/medicamentos-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IMedicamentos } from '../medicamentos.model';

@Component({
  selector: 'jhi-medicamentos-detail',
  templateUrl: './medicamentos-detail.component.html',
})
export class MedicamentosDetailComponent implements OnInit {
  medicamentos: IMedicamentos | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ medicamentos }) => {
      this.medicamentos = medicamentos;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <div *ngIf="medicamentos">
      <h2 data-cy="medicamentosDetailsHeading"><span jhiTranslate="safhApp.medicamentos.detail.title">Medicamentos</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ medicamentos.id }}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicamentos.descricao">Descricao</span></dt>
        <dd>
          <span>{{ medicamentos.descricao }}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicamentos.registroMinisterioSaude">Registro Ministerio Saude</span></dt>
        <dd>
          <span>{{ medicamentos.registroMinisterioSaude }}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicamentos.codigoBarras">Codigo Barras</span></dt>
        <dd>
          <span>{{ medicamentos.codigoBarras }}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicamentos.qtdAtual">Qtd Atual</span></dt>
        <dd>
          <span>{{ medicamentos.qtdAtual }}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicamentos.qtdMin">Qtd Min</span></dt>
        <dd>
          <span>{{ medicamentos.qtdMin }}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicamentos.qtdMax">Qtd Max</span></dt>
        <dd>
          <span>{{ medicamentos.qtdMax }}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicamentos.observacoes">Observacoes</span></dt>
        <dd>
          <span>{{ medicamentos.observacoes }}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicamentos.apresentacao">Apresentacao</span></dt>
        <dd>
          <span>{{ medicamentos.apresentacao }}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicamentos.posologiaPadrao">Posologia Padrao</span></dt>
        <dd>
          <div *ngIf="medicamentos.posologiaPadrao">
            <a [routerLink]="['/posologias', medicamentos.posologiaPadrao?.id, 'view']">{{ medicamentos.posologiaPadrao?.posologia }}</a>
          </div>
        </dd>
        <dt><span jhiTranslate="safhApp.medicamentos.fabricantes">Fabricantes</span></dt>
        <dd>
          <div *ngIf="medicamentos.fabricantes">
            <a [routerLink]="['/fabricantes', medicamentos.fabricantes?.id, 'view']">{{ medicamentos.fabricantes?.fabricante }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/medicamentos', medicamentos.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>

// src/main/webapp/app/entities/medicamentos/medicamentos-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './medicamentos.reducer';
import { IMedicamentos } from 'app/shared/model/medicamentos.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IMedicamentosDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class MedicamentosDetail extends React.Component<IMedicamentosDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { medicamentosEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="safhApp.medicamentos.detail.title">Medicamentos</Translate> [<b>{medicamentosEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="descricao">
                <Translate contentKey="safhApp.medicamentos.descricao">Descricao</Translate>
              </span>
            </dt>
            <dd>{medicamentosEntity.descricao}</dd>
            <dt>
              <span id="registroMinisterioSaude">
                <Translate contentKey="safhApp.medicamentos.registroMinisterioSaude">Registro Ministerio Saude</Translate>
              </span>
            </dt>
            <dd>{medicamentosEntity.registroMinisterioSaude}</dd>
            <dt>
              <span id="codigoBarras">
                <Translate contentKey="safhApp.medicamentos.codigoBarras">Codigo Barras</Translate>
              </span>
            </dt>
            <dd>{medicamentosEntity.codigoBarras}</dd>
            <dt>
              <span id="qtdAtual">
                <Translate contentKey="safhApp.medicamentos.qtdAtual">Qtd Atual</Translate>
              </span>
            </dt>
            <dd>{medicamentosEntity.qtdAtual}</dd>
            <dt>
              <span id="qtdMin">
                <Translate contentKey="safhApp.medicamentos.qtdMin">Qtd Min</Translate>
              </span>
            </dt>
            <dd>{medicamentosEntity.qtdMin}</dd>
            <dt>
              <span id="qtdMax">
                <Translate contentKey="safhApp.medicamentos.qtdMax">Qtd Max</Translate>
              </span>
            </dt>
            <dd>{medicamentosEntity.qtdMax}</dd>
            <dt>
              <span id="observacoes">
                <Translate contentKey="safhApp.medicamentos.observacoes">Observacoes</Translate>
              </span>
            </dt>
            <dd>{medicamentosEntity.observacoes}</dd>
            <dt>
              <span id="apresentacao">
                <Translate contentKey="safhApp.medicamentos.apresentacao">Apresentacao</Translate>
              </span>
            </dt>
            <dd>{medicamentosEntity.apresentacao}</dd>
            <dt>
              <Translate contentKey="safhApp.medicamentos.posologiaPadrao">Posologia Padrao</Translate>
            </dt>
            <dd>{medicamentosEntity.posologiaPadrao ? medicamentosEntity.posologiaPadrao.posologia : ''}</dd>
            <dt>
              <Translate contentKey="safhApp.medicamentos.fabricantes">Fabricantes</Translate>
            </dt>
            <dd>{medicamentosEntity.fabricantes ? medicamentosEntity.fabricantes.fabricante : ''}</dd>
          </dl>
          <Button tag={Link} to="/medicamentos" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/medicamentos/${medicamentosEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ medicamentos }: IRootState) => ({
  medicamentosEntity: medicamentos.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(MedicamentosDetail);
