// src/main/webapp/app/entities/clinicas/list/clinicas.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IClinicas } from '../clinicas.model';
import { ClinicasService } from '../service/clinicas.service';
import { ClinicasDeleteDialogComponent } from '../delete/clinicas-delete-dialog.component';

@Component({
  selector: 'jhi-clinicas',
  templateUrl: './clinicas.component.html',
})
export class ClinicasComponent implements OnInit {
  clinicas?: IClinicas[];
  isLoading = false;

  constructor(protected clinicasService: ClinicasService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.clinicasService.query().subscribe(
      (res: HttpResponse<IClinicas[]>) => {
        this.isLoading = false;
        this.clinicas = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IClinicas): number {
    return item.id!;
  }

  delete(clinicas: IClinicas): void {
    const modalRef = this.modalService.open(ClinicasDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.clinicas = clinicas;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="ClinicasHeading">
    <span jhiTranslate="safhApp.clinicas.home.title">Clinicas</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="safhApp.clinicas.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-clinicas"
        [routerLink]="['/clinicas/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="safhApp.clinicas.home.createLabel"> Create a new Clinicas </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="clinicas?.length === 0">
    <span jhiTranslate="safhApp.clinicas.home.notFound">No clinicas found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="clinicas && clinicas.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="safhApp.clinicas.clinica">Clinica</span></th>
          <th scope="col"><span jhiTranslate="safhApp.clinicas.descricao">Descricao</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let clinicas of clinicas; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/clinicas', clinicas.id, 'view']">{{ clinicas.id }}</a>
          </td>
          <td>{{ clinicas.clinica }}</td>
          <td>{{ clinicas.descricao }}</td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/clinicas', clinicas.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/clinicas', clinicas.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(clinicas)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/clinicas/clinicas.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudSearchAction, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities } from './clinicas.reducer';
import { IClinicas } from 'app/shared/model/clinicas.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IClinicasProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export interface IClinicasState {
  search: string;
}

export class Clinicas extends React.Component<IClinicasProps, IClinicasState> {
  state: IClinicasState = {
    search: ''
  };

  componentDidMount() {
    this.props.getEntities();
  }

  search = () => {
    if (this.state.search) {
      this.props.getSearchEntities(this.state.search);
    }
  };

  clear = () => {
    this.setState({ search: '' }, () => {
      this.props.getEntities();
    });
  };

  handleSearch = event => this.setState({ search: event.target.value });

  render() {
    const { clinicasList, match } = this.props;
    return (
      <div>
        <h2 id="clinicas-heading">
          <Translate contentKey="safhApp.clinicas.home.title">Clinicas</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="safhApp.clinicas.home.createLabel">Create a new Clinicas</Translate>
          </Link>
        </h2>
        <Row>
          <Col sm="12">
            <AvForm onSubmit={this.search}>
              <AvGroup>
                <InputGroup>
                  <AvInput
                    type="text"
                    name="search"
                    value={this.state.search}
                    onChange={this.handleSearch}
                    placeholder={translate('safhApp.clinicas.home.search')}
                  />
                  <Button className="input-group-addon">
                    <FontAwesomeIcon icon="search" />
                  </Button>
                  <Button type="reset" className="input-group-addon" onClick={this.clear}>
                    <FontAwesomeIcon icon="trash" />
                  </Button>
                </InputGroup>
              </AvGroup>
            </AvForm>
          </Col>
        </Row>
        <div className="table-responsive">
          {clinicasList && clinicasList.length > 0 ? (
            <Table responsive aria-describedby="clinicas-heading">
              <thead>
                <tr>
                  <th>
                    <Translate contentKey="global.field.id">ID</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.clinicas.clinica">Clinica</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.clinicas.descricao">Descricao</Translate>
                  </th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {clinicasList.map((clinicas, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${clinicas.id}`} color="link" size="sm">
                        {clinicas.id}
                      </Button>
                    </td>
                    <td>{clinicas.clinica}</td>
                    <td>{clinicas.descricao}</td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${clinicas.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.view">View</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${clinicas.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.edit">Edit</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${clinicas.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.delete">Delete</Translate>
                          </span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            <div className="alert alert-warning">
              <Translate contentKey="safhApp.clinicas.home.notFound">No Clinicas found</Translate>
            </div>
          )}
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ clinicas }: IRootState) => ({
  clinicasList: clinicas.entities
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Clinicas);
