// src/main/webapp/app/entities/internacoes/internacoes.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudSearchAction, ICrudGetAllAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities } from './internacoes.reducer';
import { IInternacoes } from 'app/shared/model/internacoes.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IInternacoesProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export interface IInternacoesState {
  search: string;
}

export class Internacoes extends React.Component<IInternacoesProps, IInternacoesState> {
  state: IInternacoesState = {
    search: ''
  };

  componentDidMount() {
    this.props.getEntities();
  }

  search = () => {
    if (this.state.search) {
      this.props.getSearchEntities(this.state.search);
    }
  };

  clear = () => {
    this.setState({ search: '' }, () => {
      this.props.getEntities();
    });
  };

  handleSearch = event => this.setState({ search: event.target.value });

  render() {
    const { internacoesList, match } = this.props;
    return (
      <div>
        <h2 id="internacoes-heading">
          <Translate contentKey="safhApp.internacoes.home.title">Internacoes</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="safhApp.internacoes.home.createLabel">Create a new Internacoes</Translate>
          </Link>
        </h2>
        <Row>
          <Col sm="12">
            <AvForm onSubmit={this.search}>
              <AvGroup>
                <InputGroup>
                  <AvInput
                    type="text"
                    name="search"
                    value={this.state.search}
                    onChange={this.handleSearch}
                    placeholder={translate('safhApp.internacoes.home.search')}
                  />
                  <Button className="input-group-addon">
                    <FontAwesomeIcon icon="search" />
                  </Button>
                  <Button type="reset" className="input-group-addon" onClick={this.clear}>
                    <FontAwesomeIcon icon="trash" />
                  </Button>
                </InputGroup>
              </AvGroup>
            </AvForm>
          </Col>
        </Row>
        <div className="table-responsive">
          {internacoesList && internacoesList.length > 0 ? (
            <Table responsive aria-describedby="internacoes-heading">
              <thead>
                <tr>
                  <th>
                    <Translate contentKey="global.field.id">ID</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoes.dataInternacao">Data Internacao</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoes.descricao">Descricao</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoes.pacientes">Pacientes</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoes.clinicas">Clinicas</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.internacoes.medicos">Medicos</Translate>
                  </th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {internacoesList.map((internacoes, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${internacoes.id}`} color="link" size="sm">
                        {internacoes.id}
                      </Button>
                    </td>
                    <td>
                      <TextFormat type="date" value={internacoes.dataInternacao} format={APP_LOCAL_DATE_FORMAT} />
                    </td>
                    <td>{internacoes.descricao}</td>
                    <td>
                      {internacoes.pacientes ? <Link to={`pacientes/${internacoes.pacientes.id}`}>{internacoes.pacientes.nome}</Link> : ''}
                    </td>
                    <td>
                      {internacoes.clinicas ? <Link to={`clinicas/${internacoes.clinicas.id}`}>{internacoes.clinicas.clinica}</Link> : ''}
                    </td>
                    <td>{internacoes.medicos ? <Link to={`medicos/${internacoes.medicos.id}`}>{internacoes.medicos.nome}</Link> : ''}</td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${internacoes.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.view">View</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${internacoes.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.edit">Edit</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${internacoes.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.delete">Delete</Translate>
                          </span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            <div className="alert alert-warning">
              <Translate contentKey="safhApp.internacoes.home.notFound">No Internacoes found</Translate>
            </div>
          )}
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ internacoes }: IRootState) => ({
  internacoesList: internacoes.entities
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Internacoes);

// src/main/webapp/app/entities/internacoes/list/internacoes.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IInternacoes } from '../internacoes.model';
import { InternacoesService } from '../service/internacoes.service';
import { InternacoesDeleteDialogComponent } from '../delete/internacoes-delete-dialog.component';

@Component({
  selector: 'jhi-internacoes',
  templateUrl: './internacoes.component.html',
})
export class InternacoesComponent implements OnInit {
  internacoes?: IInternacoes[];
  isLoading = false;

  constructor(protected internacoesService: InternacoesService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.internacoesService.query().subscribe(
      (res: HttpResponse<IInternacoes[]>) => {
        this.isLoading = false;
        this.internacoes = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IInternacoes): number {
    return item.id!;
  }

  delete(internacoes: IInternacoes): void {
    const modalRef = this.modalService.open(InternacoesDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.internacoes = internacoes;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="InternacoesHeading">
    <span jhiTranslate="safhApp.internacoes.home.title">Internacoes</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="safhApp.internacoes.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-internacoes"
        [routerLink]="['/internacoes/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="safhApp.internacoes.home.createLabel"> Create a new Internacoes </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="internacoes?.length === 0">
    <span jhiTranslate="safhApp.internacoes.home.notFound">No internacoes found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="internacoes && internacoes.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="safhApp.internacoes.dataInternacao">Data Internacao</span></th>
          <th scope="col"><span jhiTranslate="safhApp.internacoes.descricao">Descricao</span></th>
          <th scope="col"><span jhiTranslate="safhApp.internacoes.pacientes">Pacientes</span></th>
          <th scope="col"><span jhiTranslate="safhApp.internacoes.clinicas">Clinicas</span></th>
          <th scope="col"><span jhiTranslate="safhApp.internacoes.medicos">Medicos</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let internacoes of internacoes; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/internacoes', internacoes.id, 'view']">{{ internacoes.id }}</a>
          </td>
          <td>{{ internacoes.dataInternacao | formatMediumDate }}</td>
          <td>{{ internacoes.descricao }}</td>
          <td>
            <div *ngIf="internacoes.pacientes">
              <a [routerLink]="['/pacientes', internacoes.pacientes?.id, 'view']">{{ internacoes.pacientes?.nome }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="internacoes.clinicas">
              <a [routerLink]="['/clinicas', internacoes.clinicas?.id, 'view']">{{ internacoes.clinicas?.clinica }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="internacoes.medicos">
              <a [routerLink]="['/medicos', internacoes.medicos?.id, 'view']">{{ internacoes.medicos?.nome }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/internacoes', internacoes.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/internacoes', internacoes.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(internacoes)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
