// src/main/webapp/app/entities/medicos/medicos-detail.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs/Rx';
import { JhiEventManager } from 'ng-jhipster';

import { Medicos } from './medicos.model';
import { MedicosService } from './medicos.service';

@Component({
    selector: 'jhi-medicos-detail',
    templateUrl: './medicos-detail.component.html'
})
export class MedicosDetailComponent implements OnInit, OnDestroy {

    medicos: Medicos;
    private subscription: Subscription;
    private eventSubscriber: Subscription;

    constructor(
        private eventManager: JhiEventManager,
        private medicosService: MedicosService,
        private route: ActivatedRoute
    ) {
    }

    ngOnInit() {
        this.subscription = this.route.params.subscribe((params) => {
            this.load(params['id']);
        });
        this.registerChangeInMedicos();
    }

    load(id) {
        this.medicosService.find(id).subscribe((medicos) => {
            this.medicos = medicos;
        });
    }
    previousState() {
        window.history.back();
    }

    ngOnDestroy() {
        this.subscription.unsubscribe();
        this.eventManager.destroy(this.eventSubscriber);
    }

    registerChangeInMedicos() {
        this.eventSubscriber = this.eventManager.subscribe(
            'medicosListModification',
            (response) => this.load(this.medicos.id)
        );
    }
}


<div *ngIf="medicos">
    <h2><span jhiTranslate="safhApp.medicos.detail.title">Medicos</span> {{medicos.id}}</h2>
    <hr>
    <jhi-alert-error></jhi-alert-error>
    <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="safhApp.medicos.nome">Nome</span></dt>
        <dd>
            <span>{{medicos.nome}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicos.crm">Crm</span></dt>
        <dd>
            <span>{{medicos.crm}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicos.cpf">Cpf</span></dt>
        <dd>
            <span>{{medicos.cpf}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicos.email">Email</span></dt>
        <dd>
            <span>{{medicos.email}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicos.cep">Cep</span></dt>
        <dd>
            <span>{{medicos.cep}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicos.logradouro">Logradouro</span></dt>
        <dd>
            <span>{{medicos.logradouro}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicos.numero">Numero</span></dt>
        <dd>
            <span>{{medicos.numero}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicos.complemento">Complemento</span></dt>
        <dd>
            <span>{{medicos.complemento}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicos.bairro">Bairro</span></dt>
        <dd>
            <span>{{medicos.bairro}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicos.cidade">Cidade</span></dt>
        <dd>
            <span>{{medicos.cidade}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicos.uF">U F</span></dt>
        <dd>
            <span jhiTranslate="{{'safhApp.Estados.' + medicos.uF}}">{{medicos.uF}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.medicos.especialidades">Especialidades</span></dt>
        <dd>
            <div *ngIf="medicos.especialidades">
                <a [routerLink]="['/especialidades', medicos.especialidades?.id]">{{medicos.especialidades?.especialidade}}</a>
            </div>
        </dd>
    </dl>

    <button type="submit"
            (click)="previousState()"
            class="btn btn-info">
        <span class="fa fa-arrow-left"></span>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
    </button>

    <button type="button"
            [routerLink]="['/', { outlets: { popup: 'medicos/'+ medicos.id + '/edit'} }]"
            replaceUrl="true"
            class="btn btn-primary">
        <span class="fa fa-pencil"></span>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
    </button>
</div>

// src/main/webapp/app/entities/medicos/medicos-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './medicos.reducer';
import { IMedicos } from 'app/shared/model/medicos.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IMedicosDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class MedicosDetail extends React.Component<IMedicosDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { medicosEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="safhApp.medicos.detail.title">Medicos</Translate> [<b>{medicosEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="nome">
                <Translate contentKey="safhApp.medicos.nome">Nome</Translate>
              </span>
            </dt>
            <dd>{medicosEntity.nome}</dd>
            <dt>
              <span id="crm">
                <Translate contentKey="safhApp.medicos.crm">Crm</Translate>
              </span>
            </dt>
            <dd>{medicosEntity.crm}</dd>
            <dt>
              <span id="cpf">
                <Translate contentKey="safhApp.medicos.cpf">Cpf</Translate>
              </span>
            </dt>
            <dd>{medicosEntity.cpf}</dd>
            <dt>
              <span id="email">
                <Translate contentKey="safhApp.medicos.email">Email</Translate>
              </span>
            </dt>
            <dd>{medicosEntity.email}</dd>
            <dt>
              <span id="cep">
                <Translate contentKey="safhApp.medicos.cep">Cep</Translate>
              </span>
            </dt>
            <dd>{medicosEntity.cep}</dd>
            <dt>
              <span id="logradouro">
                <Translate contentKey="safhApp.medicos.logradouro">Logradouro</Translate>
              </span>
            </dt>
            <dd>{medicosEntity.logradouro}</dd>
            <dt>
              <span id="numero">
                <Translate contentKey="safhApp.medicos.numero">Numero</Translate>
              </span>
            </dt>
            <dd>{medicosEntity.numero}</dd>
            <dt>
              <span id="complemento">
                <Translate contentKey="safhApp.medicos.complemento">Complemento</Translate>
              </span>
            </dt>
            <dd>{medicosEntity.complemento}</dd>
            <dt>
              <span id="bairro">
                <Translate contentKey="safhApp.medicos.bairro">Bairro</Translate>
              </span>
            </dt>
            <dd>{medicosEntity.bairro}</dd>
            <dt>
              <span id="cidade">
                <Translate contentKey="safhApp.medicos.cidade">Cidade</Translate>
              </span>
            </dt>
            <dd>{medicosEntity.cidade}</dd>
            <dt>
              <span id="uF">
                <Translate contentKey="safhApp.medicos.uF">U F</Translate>
              </span>
            </dt>
            <dd>{medicosEntity.uF}</dd>
            <dt>
              <Translate contentKey="safhApp.medicos.especialidades">Especialidades</Translate>
            </dt>
            <dd>{medicosEntity.especialidades ? medicosEntity.especialidades.especialidade : ''}</dd>
          </dl>
          <Button tag={Link} to="/medicos" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/medicos/${medicosEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ medicos }: IRootState) => ({
  medicosEntity: medicos.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(MedicosDetail);
