// src/main/webapp/app/entities/medicos/medicos.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs/Rx';
import { JhiEventManager, JhiParseLinks, JhiAlertService } from 'ng-jhipster';

import { Medicos } from './medicos.model';
import { MedicosService } from './medicos.service';
import { ITEMS_PER_PAGE, Principal, ResponseWrapper } from '../../shared';

@Component({
    selector: 'jhi-medicos',
    templateUrl: './medicos.component.html'
})
export class MedicosComponent implements OnInit, OnDestroy {

    medicos: Medicos[];
    currentAccount: any;
    eventSubscriber: Subscription;
    itemsPerPage: number;
    links: any;
    page: any;
    predicate: any;
    queryCount: any;
    reverse: any;
    totalItems: number;
    currentSearch: string;

    constructor(
        private medicosService: MedicosService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private parseLinks: JhiParseLinks,
        private activatedRoute: ActivatedRoute,
        private principal: Principal
    ) {
        this.medicos = [];
        this.itemsPerPage = ITEMS_PER_PAGE;
        this.page = 0;
        this.links = {
            last: 0
        };
        this.predicate = 'id';
        this.reverse = true;
        this.currentSearch = activatedRoute.snapshot.params['search'] ? activatedRoute.snapshot.params['search'] : '';
    }

    loadAll() {
        if (this.currentSearch) {
            this.medicosService.search({
                query: this.currentSearch,
                page: this.page,
                size: this.itemsPerPage,
                sort: this.sort()
            }).subscribe(
                (res: ResponseWrapper) => this.onSuccess(res.json, res.headers),
                (res: ResponseWrapper) => this.onError(res.json)
            );
            return;
        }
        this.medicosService.query({
            page: this.page,
            size: this.itemsPerPage,
            sort: this.sort()
        }).subscribe(
            (res: ResponseWrapper) => this.onSuccess(res.json, res.headers),
            (res: ResponseWrapper) => this.onError(res.json)
        );
    }

    reset() {
        this.page = 0;
        this.medicos = [];
        this.loadAll();
    }

    loadPage(page) {
        this.page = page;
        this.loadAll();
    }

    clear() {
        this.medicos = [];
        this.links = {
            last: 0
        };
        this.page = 0;
        this.predicate = 'id';
        this.reverse = true;
        this.currentSearch = '';
        this.loadAll();
    }

    search(query) {
        if (!query) {
            return this.clear();
        }
        this.medicos = [];
        this.links = {
            last: 0
        };
        this.page = 0;
        this.predicate = '_score';
        this.reverse = false;
        this.currentSearch = query;
        this.loadAll();
    }
    ngOnInit() {
        this.loadAll();
        this.principal.identity().then((account) => {
            this.currentAccount = account;
        });
        this.registerChangeInMedicos();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: Medicos) {
        return item.id;
    }
    registerChangeInMedicos() {
        this.eventSubscriber = this.eventManager.subscribe('medicosListModification', (response) => this.reset());
    }

    sort() {
        const result = [this.predicate + ',' + (this.reverse ? 'asc' : 'desc')];
        if (this.predicate !== 'id') {
            result.push('id');
        }
        return result;
    }

    private onSuccess(data, headers) {
        this.links = this.parseLinks.parse(headers.get('link'));
        this.totalItems = headers.get('X-Total-Count');
        for (let i = 0; i < data.length; i++) {
            this.medicos.push(data[i]);
        }
    }

    private onError(error) {
        this.jhiAlertService.error(error.message, null, null);
    }
}

<div>
    <h2>
        <span jhiTranslate="safhApp.medicos.home.title">Medicos</span>
        <button class="btn btn-primary float-right jh-create-entity create-medicos" [routerLink]="['/', { outlets: { popup: ['medicos-new'] } }]">
            <span class="fa fa-plus"></span>
            <span class="hidden-sm-down"  jhiTranslate="safhApp.medicos.home.createLabel">
            Create new Medicos
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <div class="row">
        <div class="col-sm-12">
            <form name="searchForm" class="form-inline">
                <div class="input-group w-100 mt-3">
                    <input type="text" class="form-control" [(ngModel)]="currentSearch" id="currentSearch" name="currentSearch" placeholder="{{ 'safhApp.medicos.home.search' | translate }}">
                    <button class="input-group-addon btn btn-info" (click)="search(currentSearch)">
                        <span class="fa fa-search"></span>
                    </button>
                    <button class="input-group-addon btn btn-danger" (click)="clear()" *ngIf="currentSearch">
                        <span class="fa fa-trash-o"></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <br/>
    <div class="table-responsive" *ngIf="medicos">
        <table class="table table-striped">
            <thead>
            <tr jhiSort [(predicate)]="predicate" [(ascending)]="reverse" [callback]="reset.bind(this)">
            <th jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="nome"><span jhiTranslate="safhApp.medicos.nome">Nome</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="crm"><span jhiTranslate="safhApp.medicos.crm">Crm</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="cpf"><span jhiTranslate="safhApp.medicos.cpf">Cpf</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="email"><span jhiTranslate="safhApp.medicos.email">Email</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="cep"><span jhiTranslate="safhApp.medicos.cep">Cep</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="logradouro"><span jhiTranslate="safhApp.medicos.logradouro">Logradouro</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="numero"><span jhiTranslate="safhApp.medicos.numero">Numero</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="complemento"><span jhiTranslate="safhApp.medicos.complemento">Complemento</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="bairro"><span jhiTranslate="safhApp.medicos.bairro">Bairro</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="cidade"><span jhiTranslate="safhApp.medicos.cidade">Cidade</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="uF"><span jhiTranslate="safhApp.medicos.uF">U F</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="especialidades.especialidade"><span jhiTranslate="safhApp.medicos.especialidades">Especialidades</span> <span class="fa fa-sort"></span></th>
            <th></th>
            </tr>
            </thead>
            <tbody infinite-scroll (scrolled)="loadPage(page + 1)" [infiniteScrollDisabled]="page >= links['last']" [infiniteScrollDistance]="0">
            <tr *ngFor="let medicos of medicos ;trackBy: trackId">
                <td><a [routerLink]="['../medicos', medicos.id ]">{{medicos.id}}</a></td>
                <td>{{medicos.nome}}</td>
                <td>{{medicos.crm}}</td>
                <td>{{medicos.cpf}}</td>
                <td>{{medicos.email}}</td>
                <td>{{medicos.cep}}</td>
                <td>{{medicos.logradouro}}</td>
                <td>{{medicos.numero}}</td>
                <td>{{medicos.complemento}}</td>
                <td>{{medicos.bairro}}</td>
                <td>{{medicos.cidade}}</td>
                <td jhiTranslate="{{'safhApp.Estados.' + medicos.uF}}">{{medicos.uF}}</td>
                <td>
                    <div *ngIf="medicos.especialidades">
                        <a [routerLink]="['../especialidades', medicos.especialidades?.id ]" >{{medicos.especialidades?.especialidade}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['../medicos', medicos.id ]"
                                class="btn btn-info btn-sm">
                            <span class="fa fa-eye"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'medicos/'+ medicos.id + '/edit'} }]"
                                replaceUrl="true"
                                class="btn btn-primary btn-sm">
                            <span class="fa fa-pencil"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'medicos/'+ medicos.id + '/delete'} }]"
                                replaceUrl="true"
                                class="btn btn-danger btn-sm">
                            <span class="fa fa-remove"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/medicos/medicos.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudSearchAction, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities } from './medicos.reducer';
import { IMedicos } from 'app/shared/model/medicos.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IMedicosProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export interface IMedicosState {
  search: string;
}

export class Medicos extends React.Component<IMedicosProps, IMedicosState> {
  state: IMedicosState = {
    search: ''
  };

  componentDidMount() {
    this.props.getEntities();
  }

  search = () => {
    if (this.state.search) {
      this.props.getSearchEntities(this.state.search);
    }
  };

  clear = () => {
    this.setState({ search: '' }, () => {
      this.props.getEntities();
    });
  };

  handleSearch = event => this.setState({ search: event.target.value });

  render() {
    const { medicosList, match } = this.props;
    return (
      <div>
        <h2 id="medicos-heading">
          <Translate contentKey="safhApp.medicos.home.title">Medicos</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="safhApp.medicos.home.createLabel">Create a new Medicos</Translate>
          </Link>
        </h2>
        <Row>
          <Col sm="12">
            <AvForm onSubmit={this.search}>
              <AvGroup>
                <InputGroup>
                  <AvInput
                    type="text"
                    name="search"
                    value={this.state.search}
                    onChange={this.handleSearch}
                    placeholder={translate('safhApp.medicos.home.search')}
                  />
                  <Button className="input-group-addon">
                    <FontAwesomeIcon icon="search" />
                  </Button>
                  <Button type="reset" className="input-group-addon" onClick={this.clear}>
                    <FontAwesomeIcon icon="trash" />
                  </Button>
                </InputGroup>
              </AvGroup>
            </AvForm>
          </Col>
        </Row>
        <div className="table-responsive">
          {medicosList && medicosList.length > 0 ? (
            <Table responsive aria-describedby="medicos-heading">
              <thead>
                <tr>
                  <th>
                    <Translate contentKey="global.field.id">ID</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.nome">Nome</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.crm">Crm</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.cpf">Cpf</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.email">Email</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.cep">Cep</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.logradouro">Logradouro</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.numero">Numero</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.complemento">Complemento</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.bairro">Bairro</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.cidade">Cidade</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.uF">U F</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.medicos.especialidades">Especialidades</Translate>
                  </th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {medicosList.map((medicos, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${medicos.id}`} color="link" size="sm">
                        {medicos.id}
                      </Button>
                    </td>
                    <td>{medicos.nome}</td>
                    <td>{medicos.crm}</td>
                    <td>{medicos.cpf}</td>
                    <td>{medicos.email}</td>
                    <td>{medicos.cep}</td>
                    <td>{medicos.logradouro}</td>
                    <td>{medicos.numero}</td>
                    <td>{medicos.complemento}</td>
                    <td>{medicos.bairro}</td>
                    <td>{medicos.cidade}</td>
                    <td>
                      <Translate contentKey={`safhApp.Estados.${medicos.uF}`} />
                    </td>
                    <td>
                      {medicos.especialidades ? (
                        <Link to={`especialidades/${medicos.especialidades.id}`}>{medicos.especialidades.especialidade}</Link>
                      ) : (
                        ''
                      )}
                    </td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${medicos.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.view">View</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${medicos.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.edit">Edit</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${medicos.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.delete">Delete</Translate>
                          </span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            <div className="alert alert-warning">
              <Translate contentKey="safhApp.medicos.home.notFound">No Medicos found</Translate>
            </div>
          )}
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ medicos }: IRootState) => ({
  medicosList: medicos.entities
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Medicos);
