// src/main/webapp/app/entities/pacientes/pacientes.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs/Rx';
import { JhiEventManager, JhiParseLinks, JhiAlertService } from 'ng-jhipster';

import { Pacientes } from './pacientes.model';
import { PacientesService } from './pacientes.service';
import { ITEMS_PER_PAGE, Principal, ResponseWrapper } from '../../shared';

@Component({
    selector: 'jhi-pacientes',
    templateUrl: './pacientes.component.html'
})
export class PacientesComponent implements OnInit, OnDestroy {

    pacientes: Pacientes[];
    currentAccount: any;
    eventSubscriber: Subscription;
    itemsPerPage: number;
    links: any;
    page: any;
    predicate: any;
    queryCount: any;
    reverse: any;
    totalItems: number;
    currentSearch: string;

    constructor(
        private pacientesService: PacientesService,
        private jhiAlertService: JhiAlertService,
        private eventManager: JhiEventManager,
        private parseLinks: JhiParseLinks,
        private activatedRoute: ActivatedRoute,
        private principal: Principal
    ) {
        this.pacientes = [];
        this.itemsPerPage = ITEMS_PER_PAGE;
        this.page = 0;
        this.links = {
            last: 0
        };
        this.predicate = 'id';
        this.reverse = true;
        this.currentSearch = activatedRoute.snapshot.params['search'] ? activatedRoute.snapshot.params['search'] : '';
    }

    loadAll() {
        if (this.currentSearch) {
            this.pacientesService.search({
                query: this.currentSearch,
                page: this.page,
                size: this.itemsPerPage,
                sort: this.sort()
            }).subscribe(
                (res: ResponseWrapper) => this.onSuccess(res.json, res.headers),
                (res: ResponseWrapper) => this.onError(res.json)
            );
            return;
        }
        this.pacientesService.query({
            page: this.page,
            size: this.itemsPerPage,
            sort: this.sort()
        }).subscribe(
            (res: ResponseWrapper) => this.onSuccess(res.json, res.headers),
            (res: ResponseWrapper) => this.onError(res.json)
        );
    }

    reset() {
        this.page = 0;
        this.pacientes = [];
        this.loadAll();
    }

    loadPage(page) {
        this.page = page;
        this.loadAll();
    }

    clear() {
        this.pacientes = [];
        this.links = {
            last: 0
        };
        this.page = 0;
        this.predicate = 'id';
        this.reverse = true;
        this.currentSearch = '';
        this.loadAll();
    }

    search(query) {
        if (!query) {
            return this.clear();
        }
        this.pacientes = [];
        this.links = {
            last: 0
        };
        this.page = 0;
        this.predicate = '_score';
        this.reverse = false;
        this.currentSearch = query;
        this.loadAll();
    }
    ngOnInit() {
        this.loadAll();
        this.principal.identity().then((account) => {
            this.currentAccount = account;
        });
        this.registerChangeInPacientes();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: Pacientes) {
        return item.id;
    }
    registerChangeInPacientes() {
        this.eventSubscriber = this.eventManager.subscribe('pacientesListModification', (response) => this.reset());
    }

    sort() {
        const result = [this.predicate + ',' + (this.reverse ? 'asc' : 'desc')];
        if (this.predicate !== 'id') {
            result.push('id');
        }
        return result;
    }

    private onSuccess(data, headers) {
        this.links = this.parseLinks.parse(headers.get('link'));
        this.totalItems = headers.get('X-Total-Count');
        for (let i = 0; i < data.length; i++) {
            this.pacientes.push(data[i]);
        }
    }

    private onError(error) {
        this.jhiAlertService.error(error.message, null, null);
    }
}

<div>
    <h2>
        <span jhiTranslate="safhApp.pacientes.home.title">Pacientes</span>
        <button class="btn btn-primary float-right jh-create-entity create-pacientes" [routerLink]="['/', { outlets: { popup: ['pacientes-new'] } }]">
            <span class="fa fa-plus"></span>
            <span class="hidden-sm-down"  jhiTranslate="safhApp.pacientes.home.createLabel">
            Create new Pacientes
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <div class="row">
        <div class="col-sm-12">
            <form name="searchForm" class="form-inline">
                <div class="input-group w-100 mt-3">
                    <input type="text" class="form-control" [(ngModel)]="currentSearch" id="currentSearch" name="currentSearch" placeholder="{{ 'safhApp.pacientes.home.search' | translate }}">
                    <button class="input-group-addon btn btn-info" (click)="search(currentSearch)">
                        <span class="fa fa-search"></span>
                    </button>
                    <button class="input-group-addon btn btn-danger" (click)="clear()" *ngIf="currentSearch">
                        <span class="fa fa-trash-o"></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <br/>
    <div class="table-responsive" *ngIf="pacientes">
        <table class="table table-striped">
            <thead>
            <tr jhiSort [(predicate)]="predicate" [(ascending)]="reverse" [callback]="reset.bind(this)">
            <th jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="prontuario"><span jhiTranslate="safhApp.pacientes.prontuario">Prontuario</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="nome"><span jhiTranslate="safhApp.pacientes.nome">Nome</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="cpf"><span jhiTranslate="safhApp.pacientes.cpf">Cpf</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="email"><span jhiTranslate="safhApp.pacientes.email">Email</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="cep"><span jhiTranslate="safhApp.pacientes.cep">Cep</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="logradouro"><span jhiTranslate="safhApp.pacientes.logradouro">Logradouro</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="numero"><span jhiTranslate="safhApp.pacientes.numero">Numero</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="complemento"><span jhiTranslate="safhApp.pacientes.complemento">Complemento</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="bairro"><span jhiTranslate="safhApp.pacientes.bairro">Bairro</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="cidade"><span jhiTranslate="safhApp.pacientes.cidade">Cidade</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="uF"><span jhiTranslate="safhApp.pacientes.uF">U F</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="clinicas.clinica"><span jhiTranslate="safhApp.pacientes.clinicas">Clinicas</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="enfermarias.enfermaria"><span jhiTranslate="safhApp.pacientes.enfermarias">Enfermarias</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="leitos.leito"><span jhiTranslate="safhApp.pacientes.leitos">Leitos</span> <span class="fa fa-sort"></span></th>
            <th></th>
            </tr>
            </thead>
            <tbody infinite-scroll (scrolled)="loadPage(page + 1)" [infiniteScrollDisabled]="page >= links['last']" [infiniteScrollDistance]="0">
            <tr *ngFor="let pacientes of pacientes ;trackBy: trackId">
                <td><a [routerLink]="['../pacientes', pacientes.id ]">{{pacientes.id}}</a></td>
                <td>{{pacientes.prontuario}}</td>
                <td>{{pacientes.nome}}</td>
                <td>{{pacientes.cpf}}</td>
                <td>{{pacientes.email}}</td>
                <td>{{pacientes.cep}}</td>
                <td>{{pacientes.logradouro}}</td>
                <td>{{pacientes.numero}}</td>
                <td>{{pacientes.complemento}}</td>
                <td>{{pacientes.bairro}}</td>
                <td>{{pacientes.cidade}}</td>
                <td jhiTranslate="{{'safhApp.Estados.' + pacientes.uF}}">{{pacientes.uF}}</td>
                <td>
                    <div *ngIf="pacientes.clinicas">
                        <a [routerLink]="['../clinicas', pacientes.clinicas?.id ]" >{{pacientes.clinicas?.clinica}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="pacientes.enfermarias">
                        <a [routerLink]="['../enfermarias', pacientes.enfermarias?.id ]" >{{pacientes.enfermarias?.enfermaria}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="pacientes.leitos">
                        <a [routerLink]="['../leitos', pacientes.leitos?.id ]" >{{pacientes.leitos?.leito}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['../pacientes', pacientes.id ]"
                                class="btn btn-info btn-sm">
                            <span class="fa fa-eye"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'pacientes/'+ pacientes.id + '/edit'} }]"
                                replaceUrl="true"
                                class="btn btn-primary btn-sm">
                            <span class="fa fa-pencil"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'pacientes/'+ pacientes.id + '/delete'} }]"
                                replaceUrl="true"
                                class="btn btn-danger btn-sm">
                            <span class="fa fa-remove"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/pacientes/pacientes.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudSearchAction, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities } from './pacientes.reducer';
import { IPacientes } from 'app/shared/model/pacientes.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPacientesProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export interface IPacientesState {
  search: string;
}

export class Pacientes extends React.Component<IPacientesProps, IPacientesState> {
  state: IPacientesState = {
    search: ''
  };

  componentDidMount() {
    this.props.getEntities();
  }

  search = () => {
    if (this.state.search) {
      this.props.getSearchEntities(this.state.search);
    }
  };

  clear = () => {
    this.setState({ search: '' }, () => {
      this.props.getEntities();
    });
  };

  handleSearch = event => this.setState({ search: event.target.value });

  render() {
    const { pacientesList, match } = this.props;
    return (
      <div>
        <h2 id="pacientes-heading">
          <Translate contentKey="safhApp.pacientes.home.title">Pacientes</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="safhApp.pacientes.home.createLabel">Create a new Pacientes</Translate>
          </Link>
        </h2>
        <Row>
          <Col sm="12">
            <AvForm onSubmit={this.search}>
              <AvGroup>
                <InputGroup>
                  <AvInput
                    type="text"
                    name="search"
                    value={this.state.search}
                    onChange={this.handleSearch}
                    placeholder={translate('safhApp.pacientes.home.search')}
                  />
                  <Button className="input-group-addon">
                    <FontAwesomeIcon icon="search" />
                  </Button>
                  <Button type="reset" className="input-group-addon" onClick={this.clear}>
                    <FontAwesomeIcon icon="trash" />
                  </Button>
                </InputGroup>
              </AvGroup>
            </AvForm>
          </Col>
        </Row>
        <div className="table-responsive">
          {pacientesList && pacientesList.length > 0 ? (
            <Table responsive aria-describedby="pacientes-heading">
              <thead>
                <tr>
                  <th>
                    <Translate contentKey="global.field.id">ID</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.prontuario">Prontuario</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.nome">Nome</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.cpf">Cpf</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.email">Email</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.cep">Cep</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.logradouro">Logradouro</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.numero">Numero</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.complemento">Complemento</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.bairro">Bairro</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.cidade">Cidade</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.uF">U F</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.clinicas">Clinicas</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.enfermarias">Enfermarias</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.leitos">Leitos</Translate>
                  </th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {pacientesList.map((pacientes, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${pacientes.id}`} color="link" size="sm">
                        {pacientes.id}
                      </Button>
                    </td>
                    <td>{pacientes.prontuario}</td>
                    <td>{pacientes.nome}</td>
                    <td>{pacientes.cpf}</td>
                    <td>{pacientes.email}</td>
                    <td>{pacientes.cep}</td>
                    <td>{pacientes.logradouro}</td>
                    <td>{pacientes.numero}</td>
                    <td>{pacientes.complemento}</td>
                    <td>{pacientes.bairro}</td>
                    <td>{pacientes.cidade}</td>
                    <td>
                      <Translate contentKey={`safhApp.Estados.${pacientes.uF}`} />
                    </td>
                    <td>{pacientes.clinicas ? <Link to={`clinicas/${pacientes.clinicas.id}`}>{pacientes.clinicas.clinica}</Link> : ''}</td>
                    <td>
                      {pacientes.enfermarias ? (
                        <Link to={`enfermarias/${pacientes.enfermarias.id}`}>{pacientes.enfermarias.enfermaria}</Link>
                      ) : (
                        ''
                      )}
                    </td>
                    <td>{pacientes.leitos ? <Link to={`leitos/${pacientes.leitos.id}`}>{pacientes.leitos.leito}</Link> : ''}</td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${pacientes.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.view">View</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${pacientes.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.edit">Edit</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${pacientes.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.delete">Delete</Translate>
                          </span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            <div className="alert alert-warning">
              <Translate contentKey="safhApp.pacientes.home.notFound">No Pacientes found</Translate>
            </div>
          )}
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ pacientes }: IRootState) => ({
  pacientesList: pacientes.entities
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Pacientes);
