// src/main/webapp/app/entities/pacientes/pacientes-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './pacientes.reducer';
import { IPacientes } from 'app/shared/model/pacientes.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPacientesDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class PacientesDetail extends React.Component<IPacientesDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { pacientesEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="safhApp.pacientes.detail.title">Pacientes</Translate> [<b>{pacientesEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="prontuario">
                <Translate contentKey="safhApp.pacientes.prontuario">Prontuario</Translate>
              </span>
            </dt>
            <dd>{pacientesEntity.prontuario}</dd>
            <dt>
              <span id="nome">
                <Translate contentKey="safhApp.pacientes.nome">Nome</Translate>
              </span>
            </dt>
            <dd>{pacientesEntity.nome}</dd>
            <dt>
              <span id="cpf">
                <Translate contentKey="safhApp.pacientes.cpf">Cpf</Translate>
              </span>
            </dt>
            <dd>{pacientesEntity.cpf}</dd>
            <dt>
              <span id="email">
                <Translate contentKey="safhApp.pacientes.email">Email</Translate>
              </span>
            </dt>
            <dd>{pacientesEntity.email}</dd>
            <dt>
              <span id="cep">
                <Translate contentKey="safhApp.pacientes.cep">Cep</Translate>
              </span>
            </dt>
            <dd>{pacientesEntity.cep}</dd>
            <dt>
              <span id="logradouro">
                <Translate contentKey="safhApp.pacientes.logradouro">Logradouro</Translate>
              </span>
            </dt>
            <dd>{pacientesEntity.logradouro}</dd>
            <dt>
              <span id="numero">
                <Translate contentKey="safhApp.pacientes.numero">Numero</Translate>
              </span>
            </dt>
            <dd>{pacientesEntity.numero}</dd>
            <dt>
              <span id="complemento">
                <Translate contentKey="safhApp.pacientes.complemento">Complemento</Translate>
              </span>
            </dt>
            <dd>{pacientesEntity.complemento}</dd>
            <dt>
              <span id="bairro">
                <Translate contentKey="safhApp.pacientes.bairro">Bairro</Translate>
              </span>
            </dt>
            <dd>{pacientesEntity.bairro}</dd>
            <dt>
              <span id="cidade">
                <Translate contentKey="safhApp.pacientes.cidade">Cidade</Translate>
              </span>
            </dt>
            <dd>{pacientesEntity.cidade}</dd>
            <dt>
              <span id="uF">
                <Translate contentKey="safhApp.pacientes.uF">U F</Translate>
              </span>
            </dt>
            <dd>{pacientesEntity.uF}</dd>
            <dt>
              <Translate contentKey="safhApp.pacientes.clinicas">Clinicas</Translate>
            </dt>
            <dd>{pacientesEntity.clinicas ? pacientesEntity.clinicas.clinica : ''}</dd>
            <dt>
              <Translate contentKey="safhApp.pacientes.enfermarias">Enfermarias</Translate>
            </dt>
            <dd>{pacientesEntity.enfermarias ? pacientesEntity.enfermarias.enfermaria : ''}</dd>
            <dt>
              <Translate contentKey="safhApp.pacientes.leitos">Leitos</Translate>
            </dt>
            <dd>{pacientesEntity.leitos ? pacientesEntity.leitos.leito : ''}</dd>
          </dl>
          <Button tag={Link} to="/pacientes" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/pacientes/${pacientesEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ pacientes }: IRootState) => ({
  pacientesEntity: pacientes.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(PacientesDetail);

// src/main/webapp/app/entities/pacientes/pacientes-detail.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs/Rx';
import { JhiEventManager } from 'ng-jhipster';

import { Pacientes } from './pacientes.model';
import { PacientesService } from './pacientes.service';

@Component({
    selector: 'jhi-pacientes-detail',
    templateUrl: './pacientes-detail.component.html'
})
export class PacientesDetailComponent implements OnInit, OnDestroy {

    pacientes: Pacientes;
    private subscription: Subscription;
    private eventSubscriber: Subscription;

    constructor(
        private eventManager: JhiEventManager,
        private pacientesService: PacientesService,
        private route: ActivatedRoute
    ) {
    }

    ngOnInit() {
        this.subscription = this.route.params.subscribe((params) => {
            this.load(params['id']);
        });
        this.registerChangeInPacientes();
    }

    load(id) {
        this.pacientesService.find(id).subscribe((pacientes) => {
            this.pacientes = pacientes;
        });
    }
    previousState() {
        window.history.back();
    }

    ngOnDestroy() {
        this.subscription.unsubscribe();
        this.eventManager.destroy(this.eventSubscriber);
    }

    registerChangeInPacientes() {
        this.eventSubscriber = this.eventManager.subscribe(
            'pacientesListModification',
            (response) => this.load(this.pacientes.id)
        );
    }
}


<div *ngIf="pacientes">
    <h2><span jhiTranslate="safhApp.pacientes.detail.title">Pacientes</span> {{pacientes.id}}</h2>
    <hr>
    <jhi-alert-error></jhi-alert-error>
    <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="safhApp.pacientes.prontuario">Prontuario</span></dt>
        <dd>
            <span>{{pacientes.prontuario}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.pacientes.nome">Nome</span></dt>
        <dd>
            <span>{{pacientes.nome}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.pacientes.cpf">Cpf</span></dt>
        <dd>
            <span>{{pacientes.cpf}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.pacientes.email">Email</span></dt>
        <dd>
            <span>{{pacientes.email}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.pacientes.cep">Cep</span></dt>
        <dd>
            <span>{{pacientes.cep}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.pacientes.logradouro">Logradouro</span></dt>
        <dd>
            <span>{{pacientes.logradouro}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.pacientes.numero">Numero</span></dt>
        <dd>
            <span>{{pacientes.numero}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.pacientes.complemento">Complemento</span></dt>
        <dd>
            <span>{{pacientes.complemento}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.pacientes.bairro">Bairro</span></dt>
        <dd>
            <span>{{pacientes.bairro}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.pacientes.cidade">Cidade</span></dt>
        <dd>
            <span>{{pacientes.cidade}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.pacientes.uF">U F</span></dt>
        <dd>
            <span jhiTranslate="{{'safhApp.Estados.' + pacientes.uF}}">{{pacientes.uF}}</span>
        </dd>
        <dt><span jhiTranslate="safhApp.pacientes.clinicas">Clinicas</span></dt>
        <dd>
            <div *ngIf="pacientes.clinicas">
                <a [routerLink]="['/clinicas', pacientes.clinicas?.id]">{{pacientes.clinicas?.clinica}}</a>
            </div>
        </dd>
        <dt><span jhiTranslate="safhApp.pacientes.enfermarias">Enfermarias</span></dt>
        <dd>
            <div *ngIf="pacientes.enfermarias">
                <a [routerLink]="['/enfermarias', pacientes.enfermarias?.id]">{{pacientes.enfermarias?.enfermaria}}</a>
            </div>
        </dd>
        <dt><span jhiTranslate="safhApp.pacientes.leitos">Leitos</span></dt>
        <dd>
            <div *ngIf="pacientes.leitos">
                <a [routerLink]="['/leitos', pacientes.leitos?.id]">{{pacientes.leitos?.leito}}</a>
            </div>
        </dd>
    </dl>

    <button type="submit"
            (click)="previousState()"
            class="btn btn-info">
        <span class="fa fa-arrow-left"></span>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
    </button>

    <button type="button"
            [routerLink]="['/', { outlets: { popup: 'pacientes/'+ pacientes.id + '/edit'} }]"
            replaceUrl="true"
            class="btn btn-primary">
        <span class="fa fa-pencil"></span>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
    </button>
</div>
