// src/main/webapp/app/entities/pacientes/list/pacientes.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IPacientes } from '../pacientes.model';
import { PacientesService } from '../service/pacientes.service';
import { PacientesDeleteDialogComponent } from '../delete/pacientes-delete-dialog.component';

@Component({
  selector: 'jhi-pacientes',
  templateUrl: './pacientes.component.html',
})
export class PacientesComponent implements OnInit {
  pacientes?: IPacientes[];
  isLoading = false;

  constructor(protected pacientesService: PacientesService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.pacientesService.query().subscribe(
      (res: HttpResponse<IPacientes[]>) => {
        this.isLoading = false;
        this.pacientes = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IPacientes): number {
    return item.id!;
  }

  delete(pacientes: IPacientes): void {
    const modalRef = this.modalService.open(PacientesDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.pacientes = pacientes;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="PacientesHeading">
    <span jhiTranslate="safhApp.pacientes.home.title">Pacientes</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="safhApp.pacientes.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-pacientes"
        [routerLink]="['/pacientes/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="safhApp.pacientes.home.createLabel"> Create a new Pacientes </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="pacientes?.length === 0">
    <span jhiTranslate="safhApp.pacientes.home.notFound">No pacientes found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="pacientes && pacientes.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="safhApp.pacientes.prontuario">Prontuario</span></th>
          <th scope="col"><span jhiTranslate="safhApp.pacientes.nome">Nome</span></th>
          <th scope="col"><span jhiTranslate="safhApp.pacientes.cpf">Cpf</span></th>
          <th scope="col"><span jhiTranslate="safhApp.pacientes.email">Email</span></th>
          <th scope="col"><span jhiTranslate="safhApp.pacientes.cep">Cep</span></th>
          <th scope="col"><span jhiTranslate="safhApp.pacientes.logradouro">Logradouro</span></th>
          <th scope="col"><span jhiTranslate="safhApp.pacientes.numero">Numero</span></th>
          <th scope="col"><span jhiTranslate="safhApp.pacientes.complemento">Complemento</span></th>
          <th scope="col"><span jhiTranslate="safhApp.pacientes.bairro">Bairro</span></th>
          <th scope="col"><span jhiTranslate="safhApp.pacientes.cidade">Cidade</span></th>
          <th scope="col"><span jhiTranslate="safhApp.pacientes.uF">U F</span></th>
          <th scope="col"><span jhiTranslate="safhApp.pacientes.clinicas">Clinicas</span></th>
          <th scope="col"><span jhiTranslate="safhApp.pacientes.enfermarias">Enfermarias</span></th>
          <th scope="col"><span jhiTranslate="safhApp.pacientes.leitos">Leitos</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let pacientes of pacientes; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/pacientes', pacientes.id, 'view']">{{ pacientes.id }}</a>
          </td>
          <td>{{ pacientes.prontuario }}</td>
          <td>{{ pacientes.nome }}</td>
          <td>{{ pacientes.cpf }}</td>
          <td>{{ pacientes.email }}</td>
          <td>{{ pacientes.cep }}</td>
          <td>{{ pacientes.logradouro }}</td>
          <td>{{ pacientes.numero }}</td>
          <td>{{ pacientes.complemento }}</td>
          <td>{{ pacientes.bairro }}</td>
          <td>{{ pacientes.cidade }}</td>
          <td jhiTranslate="{{ 'safhApp.Estados.' + pacientes.uF }}">{{ pacientes.uF }}</td>
          <td>
            <div *ngIf="pacientes.clinicas">
              <a [routerLink]="['/clinicas', pacientes.clinicas?.id, 'view']">{{ pacientes.clinicas?.clinica }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="pacientes.enfermarias">
              <a [routerLink]="['/enfermarias', pacientes.enfermarias?.id, 'view']">{{ pacientes.enfermarias?.enfermaria }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="pacientes.leitos">
              <a [routerLink]="['/leitos', pacientes.leitos?.id, 'view']">{{ pacientes.leitos?.leito }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/pacientes', pacientes.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/pacientes', pacientes.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(pacientes)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/pacientes/pacientes.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, InputGroup, Col, Row, Table } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
import { Translate, translate, ICrudSearchAction, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getSearchEntities, getEntities } from './pacientes.reducer';
import { IPacientes } from 'app/shared/model/pacientes.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPacientesProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export interface IPacientesState {
  search: string;
}

export class Pacientes extends React.Component<IPacientesProps, IPacientesState> {
  state: IPacientesState = {
    search: ''
  };

  componentDidMount() {
    this.props.getEntities();
  }

  search = () => {
    if (this.state.search) {
      this.props.getSearchEntities(this.state.search);
    }
  };

  clear = () => {
    this.setState({ search: '' }, () => {
      this.props.getEntities();
    });
  };

  handleSearch = event => this.setState({ search: event.target.value });

  render() {
    const { pacientesList, match } = this.props;
    return (
      <div>
        <h2 id="pacientes-heading">
          <Translate contentKey="safhApp.pacientes.home.title">Pacientes</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="safhApp.pacientes.home.createLabel">Create a new Pacientes</Translate>
          </Link>
        </h2>
        <Row>
          <Col sm="12">
            <AvForm onSubmit={this.search}>
              <AvGroup>
                <InputGroup>
                  <AvInput
                    type="text"
                    name="search"
                    value={this.state.search}
                    onChange={this.handleSearch}
                    placeholder={translate('safhApp.pacientes.home.search')}
                  />
                  <Button className="input-group-addon">
                    <FontAwesomeIcon icon="search" />
                  </Button>
                  <Button type="reset" className="input-group-addon" onClick={this.clear}>
                    <FontAwesomeIcon icon="trash" />
                  </Button>
                </InputGroup>
              </AvGroup>
            </AvForm>
          </Col>
        </Row>
        <div className="table-responsive">
          {pacientesList && pacientesList.length > 0 ? (
            <Table responsive aria-describedby="pacientes-heading">
              <thead>
                <tr>
                  <th>
                    <Translate contentKey="global.field.id">ID</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.prontuario">Prontuario</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.nome">Nome</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.cpf">Cpf</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.email">Email</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.cep">Cep</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.logradouro">Logradouro</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.numero">Numero</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.complemento">Complemento</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.bairro">Bairro</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.cidade">Cidade</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.uF">U F</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.clinicas">Clinicas</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.enfermarias">Enfermarias</Translate>
                  </th>
                  <th>
                    <Translate contentKey="safhApp.pacientes.leitos">Leitos</Translate>
                  </th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {pacientesList.map((pacientes, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${pacientes.id}`} color="link" size="sm">
                        {pacientes.id}
                      </Button>
                    </td>
                    <td>{pacientes.prontuario}</td>
                    <td>{pacientes.nome}</td>
                    <td>{pacientes.cpf}</td>
                    <td>{pacientes.email}</td>
                    <td>{pacientes.cep}</td>
                    <td>{pacientes.logradouro}</td>
                    <td>{pacientes.numero}</td>
                    <td>{pacientes.complemento}</td>
                    <td>{pacientes.bairro}</td>
                    <td>{pacientes.cidade}</td>
                    <td>
                      <Translate contentKey={`safhApp.Estados.${pacientes.uF}`} />
                    </td>
                    <td>{pacientes.clinicas ? <Link to={`clinicas/${pacientes.clinicas.id}`}>{pacientes.clinicas.clinica}</Link> : ''}</td>
                    <td>
                      {pacientes.enfermarias ? (
                        <Link to={`enfermarias/${pacientes.enfermarias.id}`}>{pacientes.enfermarias.enfermaria}</Link>
                      ) : (
                        ''
                      )}
                    </td>
                    <td>{pacientes.leitos ? <Link to={`leitos/${pacientes.leitos.id}`}>{pacientes.leitos.leito}</Link> : ''}</td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${pacientes.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.view">View</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${pacientes.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.edit">Edit</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${pacientes.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.delete">Delete</Translate>
                          </span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            <div className="alert alert-warning">
              <Translate contentKey="safhApp.pacientes.home.notFound">No Pacientes found</Translate>
            </div>
          )}
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ pacientes }: IRootState) => ({
  pacientesList: pacientes.entities
});

const mapDispatchToProps = {
  getSearchEntities,
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Pacientes);
